// Generated by dedot cli

import type { GenericChainViewFunctions, GenericViewFunction } from 'dedot/types';
import type { Bytes } from 'dedot/codecs';
import type {
  PeopleWestendRuntimeRuntimeCallLike,
  PeopleWestendRuntimeProxyType,
  PalletMigrationsMbmIsOngoing,
  PalletMigrationsMbmProgress,
  PalletMigrationsMbmStatus,
} from './types.js';

export interface ChainViewFunctions extends GenericChainViewFunctions {
  /**
   * Pallet `Proxy`'s view functions
   **/
  proxy: {
    /**
     * Check if a `RuntimeCall` is allowed for a given `ProxyType`.
     *
     * @param {PeopleWestendRuntimeRuntimeCallLike} call
     * @param {PeopleWestendRuntimeProxyType} proxyType
     **/
    checkPermissions: GenericViewFunction<
      (call: PeopleWestendRuntimeRuntimeCallLike, proxyType: PeopleWestendRuntimeProxyType) => Promise<boolean>
    >;

    /**
     * Check if one `ProxyType` is a subset of another `ProxyType`.
     *
     * @param {PeopleWestendRuntimeProxyType} toCheck
     * @param {PeopleWestendRuntimeProxyType} against
     **/
    isSuperset: GenericViewFunction<
      (toCheck: PeopleWestendRuntimeProxyType, against: PeopleWestendRuntimeProxyType) => Promise<boolean>
    >;

    /**
     * Generic pallet view function
     **/
    [name: string]: GenericViewFunction;
  };
  /**
   * Pallet `MultiBlockMigrations`'s view functions
   **/
  multiBlockMigrations: {
    /**
     * Returns the ongoing status of migrations.
     **/
    ongoingStatus: GenericViewFunction<() => Promise<PalletMigrationsMbmIsOngoing>>;

    /**
     * Returns progress information about the current migration, if any.
     *
     * This function provides detailed information about the current migration's progress,
     * including the number of steps completed and the maximum allowed steps.
     **/
    progress: GenericViewFunction<() => Promise<PalletMigrationsMbmProgress | undefined>>;

    /**
     * Returns the storage prefixes affected by the current migration.
     *
     * Can be empty if the migration does not know or there are no prefixes.
     **/
    affectedPrefixes: GenericViewFunction<() => Promise<Array<Bytes>>>;

    /**
     * Returns the comprehensive status of multi-block migrations.
     **/
    status: GenericViewFunction<() => Promise<PalletMigrationsMbmStatus>>;

    /**
     * Generic pallet view function
     **/
    [name: string]: GenericViewFunction;
  };
}
