// Generated by dedot cli

import type { GenericChainErrors, GenericPalletError } from 'dedot/types';

export interface ChainErrors extends GenericChainErrors {
  /**
   * Pallet `System`'s errors
   **/
  system: {
    /**
     * The name of specification does not match between the current runtime
     * and the new runtime.
     **/
    InvalidSpecName: GenericPalletError;

    /**
     * The specification version is not allowed to decrease between the current runtime
     * and the new runtime.
     **/
    SpecVersionNeedsToIncrease: GenericPalletError;

    /**
     * Failed to extract the runtime version from the new runtime.
     *
     * Either calling `Core_version` or decoding `RuntimeVersion` failed.
     **/
    FailedToExtractRuntimeVersion: GenericPalletError;

    /**
     * Suicide called when the account has non-default composite data.
     **/
    NonDefaultComposite: GenericPalletError;

    /**
     * There is a non-zero reference count preventing the account from being purged.
     **/
    NonZeroRefCount: GenericPalletError;

    /**
     * The origin filter prevent the call to be dispatched.
     **/
    CallFiltered: GenericPalletError;

    /**
     * A multi-block migration is ongoing and prevents the current code from being replaced.
     **/
    MultiBlockMigrationsOngoing: GenericPalletError;

    /**
     * No upgrade authorized.
     **/
    NothingAuthorized: GenericPalletError;

    /**
     * The submitted code is not authorized.
     **/
    Unauthorized: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Babe`'s errors
   **/
  babe: {
    /**
     * An equivocation proof provided as part of an equivocation report is invalid.
     **/
    InvalidEquivocationProof: GenericPalletError;

    /**
     * A key ownership proof provided as part of an equivocation report is invalid.
     **/
    InvalidKeyOwnershipProof: GenericPalletError;

    /**
     * A given equivocation report is valid but already previously reported.
     **/
    DuplicateOffenceReport: GenericPalletError;

    /**
     * Submitted configuration is invalid.
     **/
    InvalidConfiguration: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Grandpa`'s errors
   **/
  grandpa: {
    /**
     * Attempt to signal GRANDPA pause when the authority set isn't live
     * (either paused or already pending pause).
     **/
    PauseFailed: GenericPalletError;

    /**
     * Attempt to signal GRANDPA resume when the authority set isn't paused
     * (either live or already pending resume).
     **/
    ResumeFailed: GenericPalletError;

    /**
     * Attempt to signal GRANDPA change with one already pending.
     **/
    ChangePending: GenericPalletError;

    /**
     * Cannot signal forced change so soon after last.
     **/
    TooSoon: GenericPalletError;

    /**
     * A key ownership proof provided as part of an equivocation report is invalid.
     **/
    InvalidKeyOwnershipProof: GenericPalletError;

    /**
     * An equivocation proof provided as part of an equivocation report is invalid.
     **/
    InvalidEquivocationProof: GenericPalletError;

    /**
     * A given equivocation report is valid but already previously reported.
     **/
    DuplicateOffenceReport: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Balances`'s errors
   **/
  balances: {
    /**
     * Vesting balance too high to send value.
     **/
    VestingBalance: GenericPalletError;

    /**
     * Account liquidity restrictions prevent withdrawal.
     **/
    LiquidityRestrictions: GenericPalletError;

    /**
     * Balance too low to send value.
     **/
    InsufficientBalance: GenericPalletError;

    /**
     * Value too low to create account due to existential deposit.
     **/
    ExistentialDeposit: GenericPalletError;

    /**
     * Transfer/payment would kill account.
     **/
    Expendability: GenericPalletError;

    /**
     * A vesting schedule already exists for this account.
     **/
    ExistingVestingSchedule: GenericPalletError;

    /**
     * Beneficiary account must pre-exist.
     **/
    DeadAccount: GenericPalletError;

    /**
     * Number of named reserves exceed `MaxReserves`.
     **/
    TooManyReserves: GenericPalletError;

    /**
     * Number of holds exceed `VariantCountOf<T::RuntimeHoldReason>`.
     **/
    TooManyHolds: GenericPalletError;

    /**
     * Number of freezes exceed `MaxFreezes`.
     **/
    TooManyFreezes: GenericPalletError;

    /**
     * The issuance cannot be modified since it is already deactivated.
     **/
    IssuanceDeactivated: GenericPalletError;

    /**
     * The delta cannot be zero.
     **/
    DeltaZero: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Session`'s errors
   **/
  session: {
    /**
     * Invalid ownership proof.
     **/
    InvalidProof: GenericPalletError;

    /**
     * No associated validator ID for account.
     **/
    NoAssociatedValidatorId: GenericPalletError;

    /**
     * Registered duplicate key.
     **/
    DuplicatedKey: GenericPalletError;

    /**
     * No keys are associated with this account.
     **/
    NoKeys: GenericPalletError;

    /**
     * Key setting account is not live, so it's impossible to associate keys.
     **/
    NoAccount: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Utility`'s errors
   **/
  utility: {
    /**
     * Too many calls batched.
     **/
    TooManyCalls: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Vesting`'s errors
   **/
  vesting: {
    /**
     * The account given is not vesting.
     **/
    NotVesting: GenericPalletError;

    /**
     * The account already has `MaxVestingSchedules` count of schedules and thus
     * cannot add another one. Consider merging existing schedules in order to add another.
     **/
    AtMaxVestingSchedules: GenericPalletError;

    /**
     * Amount being transferred is too low to create a vesting schedule.
     **/
    AmountLow: GenericPalletError;

    /**
     * An index was out of bounds of the vesting schedules.
     **/
    ScheduleIndexOutOfBounds: GenericPalletError;

    /**
     * Failed to create a new schedule because some parameter was invalid.
     **/
    InvalidScheduleParams: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `BagsList`'s errors
   **/
  bagsList: {
    /**
     * A error in the list interface implementation.
     **/
    List: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `ImOnline`'s errors
   **/
  imOnline: {
    /**
     * Non existent public key.
     **/
    InvalidKey: GenericPalletError;

    /**
     * Duplicated heartbeat.
     **/
    DuplicatedHeartbeat: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Staking`'s errors
   **/
  staking: {
    /**
     * Not a controller account.
     **/
    NotController: GenericPalletError;

    /**
     * Not a stash account.
     **/
    NotStash: GenericPalletError;

    /**
     * Stash is already bonded.
     **/
    AlreadyBonded: GenericPalletError;

    /**
     * Controller is already paired.
     **/
    AlreadyPaired: GenericPalletError;

    /**
     * Targets cannot be empty.
     **/
    EmptyTargets: GenericPalletError;

    /**
     * Duplicate index.
     **/
    DuplicateIndex: GenericPalletError;

    /**
     * Slash record index out of bounds.
     **/
    InvalidSlashIndex: GenericPalletError;

    /**
     * Cannot have a validator or nominator role, with value less than the minimum defined by
     * governance (see `MinValidatorBond` and `MinNominatorBond`). If unbonding is the
     * intention, `chill` first to remove one's role as validator/nominator.
     **/
    InsufficientBond: GenericPalletError;

    /**
     * Can not schedule more unlock chunks.
     **/
    NoMoreChunks: GenericPalletError;

    /**
     * Can not rebond without unlocking chunks.
     **/
    NoUnlockChunk: GenericPalletError;

    /**
     * Attempting to target a stash that still has funds.
     **/
    FundedTarget: GenericPalletError;

    /**
     * Invalid era to reward.
     **/
    InvalidEraToReward: GenericPalletError;

    /**
     * Invalid number of nominations.
     **/
    InvalidNumberOfNominations: GenericPalletError;

    /**
     * Items are not sorted and unique.
     **/
    NotSortedAndUnique: GenericPalletError;

    /**
     * Rewards for this era have already been claimed for this validator.
     **/
    AlreadyClaimed: GenericPalletError;

    /**
     * No nominators exist on this page.
     **/
    InvalidPage: GenericPalletError;

    /**
     * Incorrect previous history depth input provided.
     **/
    IncorrectHistoryDepth: GenericPalletError;

    /**
     * Incorrect number of slashing spans provided.
     **/
    IncorrectSlashingSpans: GenericPalletError;

    /**
     * Internal state has become somehow corrupted and the operation cannot continue.
     **/
    BadState: GenericPalletError;

    /**
     * Too many nomination targets supplied.
     **/
    TooManyTargets: GenericPalletError;

    /**
     * A nomination target was supplied that was blocked or otherwise not a validator.
     **/
    BadTarget: GenericPalletError;

    /**
     * The user has enough bond and thus cannot be chilled forcefully by an external person.
     **/
    CannotChillOther: GenericPalletError;

    /**
     * There are too many nominators in the system. Governance needs to adjust the staking
     * settings to keep things safe for the runtime.
     **/
    TooManyNominators: GenericPalletError;

    /**
     * There are too many validator candidates in the system. Governance needs to adjust the
     * staking settings to keep things safe for the runtime.
     **/
    TooManyValidators: GenericPalletError;

    /**
     * Commission is too low. Must be at least `MinCommission`.
     **/
    CommissionTooLow: GenericPalletError;

    /**
     * Some bound is not met.
     **/
    BoundNotMet: GenericPalletError;

    /**
     * Used when attempting to use deprecated controller account logic.
     **/
    ControllerDeprecated: GenericPalletError;

    /**
     * Cannot reset a ledger.
     **/
    CannotRestoreLedger: GenericPalletError;

    /**
     * Provided reward destination is not allowed.
     **/
    RewardDestinationRestricted: GenericPalletError;

    /**
     * Not enough funds available to withdraw.
     **/
    NotEnoughFunds: GenericPalletError;

    /**
     * Operation not allowed for virtual stakers.
     **/
    VirtualStakerNotAllowed: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Treasury`'s errors
   **/
  treasury: {
    /**
     * No proposal, bounty or spend at that index.
     **/
    InvalidIndex: GenericPalletError;

    /**
     * Too many approvals in the queue.
     **/
    TooManyApprovals: GenericPalletError;

    /**
     * The spend origin is valid but the amount it is allowed to spend is lower than the
     * amount to be spent.
     **/
    InsufficientPermission: GenericPalletError;

    /**
     * Proposal has not been approved.
     **/
    ProposalNotApproved: GenericPalletError;

    /**
     * The balance of the asset kind is not convertible to the balance of the native asset.
     **/
    FailedToConvertBalance: GenericPalletError;

    /**
     * The spend has expired and cannot be claimed.
     **/
    SpendExpired: GenericPalletError;

    /**
     * The spend is not yet eligible for payout.
     **/
    EarlyPayout: GenericPalletError;

    /**
     * The payment has already been attempted.
     **/
    AlreadyAttempted: GenericPalletError;

    /**
     * There was some issue with the mechanism of payment.
     **/
    PayoutError: GenericPalletError;

    /**
     * The payout was not yet attempted/claimed.
     **/
    NotAttempted: GenericPalletError;

    /**
     * The payment has neither failed nor succeeded yet.
     **/
    Inconclusive: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `ConvictionVoting`'s errors
   **/
  convictionVoting: {
    /**
     * Poll is not ongoing.
     **/
    NotOngoing: GenericPalletError;

    /**
     * The given account did not vote on the poll.
     **/
    NotVoter: GenericPalletError;

    /**
     * The actor has no permission to conduct the action.
     **/
    NoPermission: GenericPalletError;

    /**
     * The actor has no permission to conduct the action right now but will do in the future.
     **/
    NoPermissionYet: GenericPalletError;

    /**
     * The account is already delegating.
     **/
    AlreadyDelegating: GenericPalletError;

    /**
     * The account currently has votes attached to it and the operation cannot succeed until
     * these are removed through `remove_vote`.
     **/
    AlreadyVoting: GenericPalletError;

    /**
     * Too high a balance was provided that the account cannot afford.
     **/
    InsufficientFunds: GenericPalletError;

    /**
     * The account is not currently delegating.
     **/
    NotDelegating: GenericPalletError;

    /**
     * Delegation to oneself makes no sense.
     **/
    Nonsense: GenericPalletError;

    /**
     * Maximum number of votes reached.
     **/
    MaxVotesReached: GenericPalletError;

    /**
     * The class must be supplied since it is not easily determinable from the state.
     **/
    ClassNeeded: GenericPalletError;

    /**
     * The class ID supplied is invalid.
     **/
    BadClass: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Referenda`'s errors
   **/
  referenda: {
    /**
     * Referendum is not ongoing.
     **/
    NotOngoing: GenericPalletError;

    /**
     * Referendum's decision deposit is already paid.
     **/
    HasDeposit: GenericPalletError;

    /**
     * The track identifier given was invalid.
     **/
    BadTrack: GenericPalletError;

    /**
     * There are already a full complement of referenda in progress for this track.
     **/
    Full: GenericPalletError;

    /**
     * The queue of the track is empty.
     **/
    QueueEmpty: GenericPalletError;

    /**
     * The referendum index provided is invalid in this context.
     **/
    BadReferendum: GenericPalletError;

    /**
     * There was nothing to do in the advancement.
     **/
    NothingToDo: GenericPalletError;

    /**
     * No track exists for the proposal origin.
     **/
    NoTrack: GenericPalletError;

    /**
     * Any deposit cannot be refunded until after the decision is over.
     **/
    Unfinished: GenericPalletError;

    /**
     * The deposit refunder is not the depositor.
     **/
    NoPermission: GenericPalletError;

    /**
     * The deposit cannot be refunded since none was made.
     **/
    NoDeposit: GenericPalletError;

    /**
     * The referendum status is invalid for this operation.
     **/
    BadStatus: GenericPalletError;

    /**
     * The preimage does not exist.
     **/
    PreimageNotExist: GenericPalletError;

    /**
     * The preimage is stored with a different length than the one provided.
     **/
    PreimageStoredWithDifferentLength: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `FellowshipCollective`'s errors
   **/
  fellowshipCollective: {
    /**
     * Account is already a member.
     **/
    AlreadyMember: GenericPalletError;

    /**
     * Account is not a member.
     **/
    NotMember: GenericPalletError;

    /**
     * The given poll index is unknown or has closed.
     **/
    NotPolling: GenericPalletError;

    /**
     * The given poll is still ongoing.
     **/
    Ongoing: GenericPalletError;

    /**
     * There are no further records to be removed.
     **/
    NoneRemaining: GenericPalletError;

    /**
     * Unexpected error in state.
     **/
    Corruption: GenericPalletError;

    /**
     * The member's rank is too low to vote.
     **/
    RankTooLow: GenericPalletError;

    /**
     * The information provided is incorrect.
     **/
    InvalidWitness: GenericPalletError;

    /**
     * The origin is not sufficiently privileged to do the operation.
     **/
    NoPermission: GenericPalletError;

    /**
     * The new member to exchange is the same as the old member
     **/
    SameMember: GenericPalletError;

    /**
     * The max member count for the rank has been reached.
     **/
    TooManyMembers: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `FellowshipReferenda`'s errors
   **/
  fellowshipReferenda: {
    /**
     * Referendum is not ongoing.
     **/
    NotOngoing: GenericPalletError;

    /**
     * Referendum's decision deposit is already paid.
     **/
    HasDeposit: GenericPalletError;

    /**
     * The track identifier given was invalid.
     **/
    BadTrack: GenericPalletError;

    /**
     * There are already a full complement of referenda in progress for this track.
     **/
    Full: GenericPalletError;

    /**
     * The queue of the track is empty.
     **/
    QueueEmpty: GenericPalletError;

    /**
     * The referendum index provided is invalid in this context.
     **/
    BadReferendum: GenericPalletError;

    /**
     * There was nothing to do in the advancement.
     **/
    NothingToDo: GenericPalletError;

    /**
     * No track exists for the proposal origin.
     **/
    NoTrack: GenericPalletError;

    /**
     * Any deposit cannot be refunded until after the decision is over.
     **/
    Unfinished: GenericPalletError;

    /**
     * The deposit refunder is not the depositor.
     **/
    NoPermission: GenericPalletError;

    /**
     * The deposit cannot be refunded since none was made.
     **/
    NoDeposit: GenericPalletError;

    /**
     * The referendum status is invalid for this operation.
     **/
    BadStatus: GenericPalletError;

    /**
     * The preimage does not exist.
     **/
    PreimageNotExist: GenericPalletError;

    /**
     * The preimage is stored with a different length than the one provided.
     **/
    PreimageStoredWithDifferentLength: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Whitelist`'s errors
   **/
  whitelist: {
    /**
     * The preimage of the call hash could not be loaded.
     **/
    UnavailablePreImage: GenericPalletError;

    /**
     * The call could not be decoded.
     **/
    UndecodableCall: GenericPalletError;

    /**
     * The weight of the decoded call was higher than the witness.
     **/
    InvalidCallWeightWitness: GenericPalletError;

    /**
     * The call was not whitelisted.
     **/
    CallIsNotWhitelisted: GenericPalletError;

    /**
     * The call was already whitelisted; No-Op.
     **/
    CallAlreadyWhitelisted: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Scheduler`'s errors
   **/
  scheduler: {
    /**
     * Failed to schedule a call
     **/
    FailedToSchedule: GenericPalletError;

    /**
     * Cannot find the scheduled call.
     **/
    NotFound: GenericPalletError;

    /**
     * Given target block number is in the past.
     **/
    TargetBlockNumberInPast: GenericPalletError;

    /**
     * Reschedule failed because it does not change scheduled time.
     **/
    RescheduleNoChange: GenericPalletError;

    /**
     * Attempt to use a non-named function on a named task.
     **/
    Named: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Preimage`'s errors
   **/
  preimage: {
    /**
     * Preimage is too large to store on-chain.
     **/
    TooBig: GenericPalletError;

    /**
     * Preimage has already been noted on-chain.
     **/
    AlreadyNoted: GenericPalletError;

    /**
     * The user is not authorized to perform this action.
     **/
    NotAuthorized: GenericPalletError;

    /**
     * The preimage cannot be removed since it has not yet been noted.
     **/
    NotNoted: GenericPalletError;

    /**
     * A preimage may not be removed when there are outstanding requests.
     **/
    Requested: GenericPalletError;

    /**
     * The preimage request cannot be removed since no outstanding requests exist.
     **/
    NotRequested: GenericPalletError;

    /**
     * More than `MAX_HASH_UPGRADE_BULK_COUNT` hashes were requested to be upgraded at once.
     **/
    TooMany: GenericPalletError;

    /**
     * Too few hashes were requested to be upgraded (i.e. zero).
     **/
    TooFew: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Identity`'s errors
   **/
  identity: {
    /**
     * Too many subs-accounts.
     **/
    TooManySubAccounts: GenericPalletError;

    /**
     * Account isn't found.
     **/
    NotFound: GenericPalletError;

    /**
     * Account isn't named.
     **/
    NotNamed: GenericPalletError;

    /**
     * Empty index.
     **/
    EmptyIndex: GenericPalletError;

    /**
     * Fee is changed.
     **/
    FeeChanged: GenericPalletError;

    /**
     * No identity found.
     **/
    NoIdentity: GenericPalletError;

    /**
     * Sticky judgement.
     **/
    StickyJudgement: GenericPalletError;

    /**
     * Judgement given.
     **/
    JudgementGiven: GenericPalletError;

    /**
     * Invalid judgement.
     **/
    InvalidJudgement: GenericPalletError;

    /**
     * The index is invalid.
     **/
    InvalidIndex: GenericPalletError;

    /**
     * The target is invalid.
     **/
    InvalidTarget: GenericPalletError;

    /**
     * Maximum amount of registrars reached. Cannot add any more.
     **/
    TooManyRegistrars: GenericPalletError;

    /**
     * Account ID is already named.
     **/
    AlreadyClaimed: GenericPalletError;

    /**
     * Sender is not a sub-account.
     **/
    NotSub: GenericPalletError;

    /**
     * Sub-account isn't owned by sender.
     **/
    NotOwned: GenericPalletError;

    /**
     * The provided judgement was for a different identity.
     **/
    JudgementForDifferentIdentity: GenericPalletError;

    /**
     * Error that occurs when there is an issue paying for judgement.
     **/
    JudgementPaymentFailed: GenericPalletError;

    /**
     * The provided suffix is too long.
     **/
    InvalidSuffix: GenericPalletError;

    /**
     * The sender does not have permission to issue a username.
     **/
    NotUsernameAuthority: GenericPalletError;

    /**
     * The authority cannot allocate any more usernames.
     **/
    NoAllocation: GenericPalletError;

    /**
     * The signature on a username was not valid.
     **/
    InvalidSignature: GenericPalletError;

    /**
     * Setting this username requires a signature, but none was provided.
     **/
    RequiresSignature: GenericPalletError;

    /**
     * The username does not meet the requirements.
     **/
    InvalidUsername: GenericPalletError;

    /**
     * The username is already taken.
     **/
    UsernameTaken: GenericPalletError;

    /**
     * The requested username does not exist.
     **/
    NoUsername: GenericPalletError;

    /**
     * The username cannot be forcefully removed because it can still be accepted.
     **/
    NotExpired: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Proxy`'s errors
   **/
  proxy: {
    /**
     * There are too many proxies registered or too many announcements pending.
     **/
    TooMany: GenericPalletError;

    /**
     * Proxy registration not found.
     **/
    NotFound: GenericPalletError;

    /**
     * Sender is not a proxy of the account to be proxied.
     **/
    NotProxy: GenericPalletError;

    /**
     * A call which is incompatible with the proxy type's filter was attempted.
     **/
    Unproxyable: GenericPalletError;

    /**
     * Account is already a proxy.
     **/
    Duplicate: GenericPalletError;

    /**
     * Call may not be made by proxy because it may escalate its privileges.
     **/
    NoPermission: GenericPalletError;

    /**
     * Announcement, if made at all, was made too recently.
     **/
    Unannounced: GenericPalletError;

    /**
     * Cannot add self as proxy.
     **/
    NoSelfProxy: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Multisig`'s errors
   **/
  multisig: {
    /**
     * Threshold must be 2 or greater.
     **/
    MinimumThreshold: GenericPalletError;

    /**
     * Call is already approved by this signatory.
     **/
    AlreadyApproved: GenericPalletError;

    /**
     * Call doesn't need any (more) approvals.
     **/
    NoApprovalsNeeded: GenericPalletError;

    /**
     * There are too few signatories in the list.
     **/
    TooFewSignatories: GenericPalletError;

    /**
     * There are too many signatories in the list.
     **/
    TooManySignatories: GenericPalletError;

    /**
     * The signatories were provided out of order; they should be ordered.
     **/
    SignatoriesOutOfOrder: GenericPalletError;

    /**
     * The sender was contained in the other signatories; it shouldn't be.
     **/
    SenderInSignatories: GenericPalletError;

    /**
     * Multisig operation not found when attempting to cancel.
     **/
    NotFound: GenericPalletError;

    /**
     * Only the account that originally created the multisig is able to cancel it.
     **/
    NotOwner: GenericPalletError;

    /**
     * No timepoint was given, yet the multisig operation is already underway.
     **/
    NoTimepoint: GenericPalletError;

    /**
     * A different timepoint was given to the multisig operation that is underway.
     **/
    WrongTimepoint: GenericPalletError;

    /**
     * A timepoint was given, yet no multisig operation is underway.
     **/
    UnexpectedTimepoint: GenericPalletError;

    /**
     * The maximum weight information provided was too low.
     **/
    MaxWeightTooLow: GenericPalletError;

    /**
     * The data to be stored is already stored.
     **/
    AlreadyStored: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `ElectionProviderMultiPhase`'s errors
   **/
  electionProviderMultiPhase: {
    /**
     * Submission was too early.
     **/
    PreDispatchEarlySubmission: GenericPalletError;

    /**
     * Wrong number of winners presented.
     **/
    PreDispatchWrongWinnerCount: GenericPalletError;

    /**
     * Submission was too weak, score-wise.
     **/
    PreDispatchWeakSubmission: GenericPalletError;

    /**
     * The queue was full, and the solution was not better than any of the existing ones.
     **/
    SignedQueueFull: GenericPalletError;

    /**
     * The origin failed to pay the deposit.
     **/
    SignedCannotPayDeposit: GenericPalletError;

    /**
     * Witness data to dispatchable is invalid.
     **/
    SignedInvalidWitness: GenericPalletError;

    /**
     * The signed submission consumes too much weight
     **/
    SignedTooMuchWeight: GenericPalletError;

    /**
     * OCW submitted solution for wrong round
     **/
    OcwCallWrongEra: GenericPalletError;

    /**
     * Snapshot metadata should exist but didn't.
     **/
    MissingSnapshotMetadata: GenericPalletError;

    /**
     * `Self::insert_submission` returned an invalid index.
     **/
    InvalidSubmissionIndex: GenericPalletError;

    /**
     * The call is not allowed at this point.
     **/
    CallNotAllowed: GenericPalletError;

    /**
     * The fallback failed
     **/
    FallbackFailed: GenericPalletError;

    /**
     * Some bound not met
     **/
    BoundNotMet: GenericPalletError;

    /**
     * Submitted solution has too many winners
     **/
    TooManyWinners: GenericPalletError;

    /**
     * Submission was prepared for a different round.
     **/
    PreDispatchDifferentRound: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Bounties`'s errors
   **/
  bounties: {
    /**
     * Proposer's balance is too low.
     **/
    InsufficientProposersBalance: GenericPalletError;

    /**
     * No proposal or bounty at that index.
     **/
    InvalidIndex: GenericPalletError;

    /**
     * The reason given is just too big.
     **/
    ReasonTooBig: GenericPalletError;

    /**
     * The bounty status is unexpected.
     **/
    UnexpectedStatus: GenericPalletError;

    /**
     * Require bounty curator.
     **/
    RequireCurator: GenericPalletError;

    /**
     * Invalid bounty value.
     **/
    InvalidValue: GenericPalletError;

    /**
     * Invalid bounty fee.
     **/
    InvalidFee: GenericPalletError;

    /**
     * A bounty payout is pending.
     * To cancel the bounty, you must unassign and slash the curator.
     **/
    PendingPayout: GenericPalletError;

    /**
     * The bounties cannot be claimed/closed because it's still in the countdown period.
     **/
    Premature: GenericPalletError;

    /**
     * The bounty cannot be closed because it has active child bounties.
     **/
    HasActiveChildBounty: GenericPalletError;

    /**
     * Too many approvals are already queued.
     **/
    TooManyQueued: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `ChildBounties`'s errors
   **/
  childBounties: {
    /**
     * The parent bounty is not in active state.
     **/
    ParentBountyNotActive: GenericPalletError;

    /**
     * The bounty balance is not enough to add new child-bounty.
     **/
    InsufficientBountyBalance: GenericPalletError;

    /**
     * Number of child bounties exceeds limit `MaxActiveChildBountyCount`.
     **/
    TooManyChildBounties: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `NominationPools`'s errors
   **/
  nominationPools: {
    /**
     * A (bonded) pool id does not exist.
     **/
    PoolNotFound: GenericPalletError;

    /**
     * An account is not a member.
     **/
    PoolMemberNotFound: GenericPalletError;

    /**
     * A reward pool does not exist. In all cases this is a system logic error.
     **/
    RewardPoolNotFound: GenericPalletError;

    /**
     * A sub pool does not exist.
     **/
    SubPoolsNotFound: GenericPalletError;

    /**
     * An account is already delegating in another pool. An account may only belong to one
     * pool at a time.
     **/
    AccountBelongsToOtherPool: GenericPalletError;

    /**
     * The member is fully unbonded (and thus cannot access the bonded and reward pool
     * anymore to, for example, collect rewards).
     **/
    FullyUnbonding: GenericPalletError;

    /**
     * The member cannot unbond further chunks due to reaching the limit.
     **/
    MaxUnbondingLimit: GenericPalletError;

    /**
     * None of the funds can be withdrawn yet because the bonding duration has not passed.
     **/
    CannotWithdrawAny: GenericPalletError;

    /**
     * The amount does not meet the minimum bond to either join or create a pool.
     *
     * The depositor can never unbond to a value less than `Pallet::depositor_min_bond`. The
     * caller does not have nominating permissions for the pool. Members can never unbond to a
     * value below `MinJoinBond`.
     **/
    MinimumBondNotMet: GenericPalletError;

    /**
     * The transaction could not be executed due to overflow risk for the pool.
     **/
    OverflowRisk: GenericPalletError;

    /**
     * A pool must be in [`PoolState::Destroying`] in order for the depositor to unbond or for
     * other members to be permissionlessly unbonded.
     **/
    NotDestroying: GenericPalletError;

    /**
     * The caller does not have nominating permissions for the pool.
     **/
    NotNominator: GenericPalletError;

    /**
     * Either a) the caller cannot make a valid kick or b) the pool is not destroying.
     **/
    NotKickerOrDestroying: GenericPalletError;

    /**
     * The pool is not open to join
     **/
    NotOpen: GenericPalletError;

    /**
     * The system is maxed out on pools.
     **/
    MaxPools: GenericPalletError;

    /**
     * Too many members in the pool or system.
     **/
    MaxPoolMembers: GenericPalletError;

    /**
     * The pools state cannot be changed.
     **/
    CanNotChangeState: GenericPalletError;

    /**
     * The caller does not have adequate permissions.
     **/
    DoesNotHavePermission: GenericPalletError;

    /**
     * Metadata exceeds [`Config::MaxMetadataLen`]
     **/
    MetadataExceedsMaxLen: GenericPalletError;

    /**
     * Some error occurred that should never happen. This should be reported to the
     * maintainers.
     **/
    Defensive: GenericPalletError;

    /**
     * Partial unbonding now allowed permissionlessly.
     **/
    PartialUnbondNotAllowedPermissionlessly: GenericPalletError;

    /**
     * The pool's max commission cannot be set higher than the existing value.
     **/
    MaxCommissionRestricted: GenericPalletError;

    /**
     * The supplied commission exceeds the max allowed commission.
     **/
    CommissionExceedsMaximum: GenericPalletError;

    /**
     * The supplied commission exceeds global maximum commission.
     **/
    CommissionExceedsGlobalMaximum: GenericPalletError;

    /**
     * Not enough blocks have surpassed since the last commission update.
     **/
    CommissionChangeThrottled: GenericPalletError;

    /**
     * The submitted changes to commission change rate are not allowed.
     **/
    CommissionChangeRateNotAllowed: GenericPalletError;

    /**
     * There is no pending commission to claim.
     **/
    NoPendingCommission: GenericPalletError;

    /**
     * No commission current has been set.
     **/
    NoCommissionCurrentSet: GenericPalletError;

    /**
     * Pool id currently in use.
     **/
    PoolIdInUse: GenericPalletError;

    /**
     * Pool id provided is not correct/usable.
     **/
    InvalidPoolId: GenericPalletError;

    /**
     * Bonding extra is restricted to the exact pending reward amount.
     **/
    BondExtraRestricted: GenericPalletError;

    /**
     * No imbalance in the ED deposit for the pool.
     **/
    NothingToAdjust: GenericPalletError;

    /**
     * No slash pending that can be applied to the member.
     **/
    NothingToSlash: GenericPalletError;

    /**
     * The pool or member delegation has already migrated to delegate stake.
     **/
    AlreadyMigrated: GenericPalletError;

    /**
     * The pool or member delegation has not migrated yet to delegate stake.
     **/
    NotMigrated: GenericPalletError;

    /**
     * This call is not allowed in the current state of the pallet.
     **/
    NotSupported: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GearProgram`'s errors
   **/
  gearProgram: {
    DuplicateItem: GenericPalletError;
    ProgramNotFound: GenericPalletError;
    NotActiveProgram: GenericPalletError;
    CannotFindDataForPage: GenericPalletError;
    ProgramCodeNotFound: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GearMessenger`'s errors
   **/
  gearMessenger: {
    /**
     * Occurs when given key already exists in queue.
     **/
    QueueDuplicateKey: GenericPalletError;

    /**
     * Occurs when queue's element wasn't found in storage.
     **/
    QueueElementNotFound: GenericPalletError;

    /**
     * Occurs when queue's head should contain value,
     * but it's empty for some reason.
     **/
    QueueHeadShouldBeSet: GenericPalletError;

    /**
     * Occurs when queue's head should be empty,
     * but it contains value for some reason.
     **/
    QueueHeadShouldNotBeSet: GenericPalletError;

    /**
     * Occurs when queue's tail element contains link
     * to the next element.
     **/
    QueueTailHasNextKey: GenericPalletError;

    /**
     * Occurs when while searching queue's pre-tail,
     * element wasn't found.
     **/
    QueueTailParentNotFound: GenericPalletError;

    /**
     * Occurs when queue's tail should contain value,
     * but it's empty for some reason.
     **/
    QueueTailShouldBeSet: GenericPalletError;

    /**
     * Occurs when queue's tail should be empty,
     * but it contains value for some reason.
     **/
    QueueTailShouldNotBeSet: GenericPalletError;

    /**
     * Occurs when given value already exists in mailbox.
     **/
    MailboxDuplicateKey: GenericPalletError;

    /**
     * Occurs when mailbox's element wasn't found in storage.
     **/
    MailboxElementNotFound: GenericPalletError;

    /**
     * Occurs when given value already exists in waitlist.
     **/
    WaitlistDuplicateKey: GenericPalletError;

    /**
     * Occurs when waitlist's element wasn't found in storage.
     **/
    WaitlistElementNotFound: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GearScheduler`'s errors
   **/
  gearScheduler: {
    /**
     * Occurs when given task already exists in task pool.
     **/
    DuplicateTask: GenericPalletError;

    /**
     * Occurs when task wasn't found in storage.
     **/
    TaskNotFound: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GearGas`'s errors
   **/
  gearGas: {
    Forbidden: GenericPalletError;
    NodeAlreadyExists: GenericPalletError;
    InsufficientBalance: GenericPalletError;
    NodeNotFound: GenericPalletError;
    NodeWasConsumed: GenericPalletError;

    /**
     * Errors stating that gas tree has been invalidated
     **/
    ParentIsLost: GenericPalletError;
    ParentHasNoChildren: GenericPalletError;

    /**
     * Output of `Tree::consume` procedure that wasn't expected.
     *
     * Outputs of consumption procedure are determined. The error is returned
     * when unexpected one occurred. That signals, that algorithm works wrong
     * and expected invariants are not correct.
     **/
    UnexpectedConsumeOutput: GenericPalletError;

    /**
     * Node type that can't occur if algorithm work well
     **/
    UnexpectedNodeType: GenericPalletError;

    /**
     * Value must have been caught, but was missed or blocked (for more info see `ValueNode::catch_value`).
     **/
    ValueIsNotCaught: GenericPalletError;

    /**
     * Value must have been caught or moved upstream, but was blocked (for more info see `ValueNode::catch_value`).
     **/
    ValueIsBlocked: GenericPalletError;

    /**
     * Value must have been blocked, but was either moved or caught (for more info see `ValueNode::catch_value`).
     **/
    ValueIsNotBlocked: GenericPalletError;

    /**
     * `GasTree::consume` called on node, which has some balance locked.
     **/
    ConsumedWithLock: GenericPalletError;

    /**
     * `GasTree::consume` called on node, which has some system reservation.
     **/
    ConsumedWithSystemReservation: GenericPalletError;

    /**
     * `GasTree::create` called with some value amount leading to
     * the total value overflow.
     **/
    TotalValueIsOverflowed: GenericPalletError;

    /**
     * Either `GasTree::consume` or `GasTree::spent` called on a node creating
     * negative imbalance which leads to the total value drop below 0.
     **/
    TotalValueIsUnderflowed: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `Gear`'s errors
   **/
  gear: {
    /**
     * Message wasn't found in the mailbox.
     **/
    MessageNotFound: GenericPalletError;

    /**
     * Not enough balance to execute an action.
     *
     * Usually occurs when the gas_limit specified is such that the origin account can't afford the message.
     **/
    InsufficientBalance: GenericPalletError;

    /**
     * Gas limit too high.
     *
     * Occurs when an extrinsic's declared `gas_limit` is greater than a block's maximum gas limit.
     **/
    GasLimitTooHigh: GenericPalletError;

    /**
     * Program already exists.
     *
     * Occurs if a program with some specific program id already exists in program storage.
     **/
    ProgramAlreadyExists: GenericPalletError;

    /**
     * Program is terminated.
     *
     * Program init failed, so such message destination is no longer unavailable.
     **/
    InactiveProgram: GenericPalletError;

    /**
     * Message gas tree is not found.
     *
     * When a message claimed from the mailbox has a corrupted or non-extant gas tree associated.
     **/
    NoMessageTree: GenericPalletError;

    /**
     * Code already exists.
     *
     * Occurs when trying to save to storage a program code that has been saved there.
     **/
    CodeAlreadyExists: GenericPalletError;

    /**
     * Code does not exist.
     *
     * Occurs when trying to get a program code from storage, that doesn't exist.
     **/
    CodeDoesntExist: GenericPalletError;

    /**
     * The code supplied to `upload_code` or `upload_program` exceeds the limit specified in the
     * current schedule.
     **/
    CodeTooLarge: GenericPalletError;

    /**
     * Failed to create a program.
     **/
    ProgramConstructionFailed: GenericPalletError;

    /**
     * Message queue processing is disabled.
     **/
    MessageQueueProcessingDisabled: GenericPalletError;

    /**
     * Block count doesn't cover MinimalResumePeriod.
     **/
    ResumePeriodLessThanMinimal: GenericPalletError;

    /**
     * Program with the specified id is not found.
     **/
    ProgramNotFound: GenericPalletError;

    /**
     * Gear::run() already included in current block.
     **/
    GearRunAlreadyInBlock: GenericPalletError;

    /**
     * The program rent logic is disabled.
     **/
    ProgramRentDisabled: GenericPalletError;

    /**
     * Program is active.
     **/
    ActiveProgram: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `StakingRewards`'s errors
   **/
  stakingRewards: {
    /**
     * Pool not replenished due to error.
     **/
    FailureToRefillPool: GenericPalletError;

    /**
     * Failure to withdraw funds from the rewards pool.
     **/
    FailureToWithdrawFromPool: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GearVoucher`'s errors
   **/
  gearVoucher: {
    /**
     * The origin is not eligible to execute call.
     **/
    BadOrigin: GenericPalletError;

    /**
     * Error trying transfer balance to/from voucher account.
     **/
    BalanceTransfer: GenericPalletError;

    /**
     * Destination program is not in whitelisted set for voucher.
     **/
    InappropriateDestination: GenericPalletError;

    /**
     * Voucher with given identifier doesn't exist for given spender id.
     **/
    InexistentVoucher: GenericPalletError;

    /**
     * Voucher still valid and couldn't be revoked.
     **/
    IrrevocableYet: GenericPalletError;

    /**
     * Try to whitelist more programs than allowed.
     **/
    MaxProgramsLimitExceeded: GenericPalletError;

    /**
     * Failed to query destination of the prepaid call.
     **/
    UnknownDestination: GenericPalletError;

    /**
     * Voucher has expired and couldn't be used.
     **/
    VoucherExpired: GenericPalletError;

    /**
     * Voucher issue/prolongation duration out of [min; max] constants.
     **/
    DurationOutOfBounds: GenericPalletError;

    /**
     * Voucher update function tries to cut voucher ability of code upload.
     **/
    CodeUploadingEnabled: GenericPalletError;

    /**
     * Voucher is disabled for code uploading, but requested.
     **/
    CodeUploadingDisabled: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GearBank`'s errors
   **/
  gearBank: {
    /**
     * Insufficient user balance.
     **/
    InsufficientBalance: GenericPalletError;

    /**
     * Insufficient user's bank account gas balance.
     **/
    InsufficientGasBalance: GenericPalletError;

    /**
     * Insufficient user's bank account gas balance.
     **/
    InsufficientValueBalance: GenericPalletError;

    /**
     * Insufficient bank account balance.
     * **Must be unreachable in Gear main protocol.**
     **/
    InsufficientBankBalance: GenericPalletError;

    /**
     * Deposit of funds that will not keep bank account alive.
     * **Must be unreachable in Gear main protocol.**
     **/
    InsufficientDeposit: GenericPalletError;

    /**
     * Overflow during funds transfer.
     * **Must be unreachable in Gear main protocol.**
     **/
    Overflow: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GearEthBridge`'s errors
   **/
  gearEthBridge: {
    /**
     * The error happens when bridge queue is temporarily overflowed
     * and needs cleanup to proceed.
     **/
    BridgeCleanupRequired: GenericPalletError;

    /**
     * The error happens when bridge got called before
     * proper initialization after deployment.
     **/
    BridgeIsNotYetInitialized: GenericPalletError;

    /**
     * The error happens when bridge got called when paused.
     **/
    BridgeIsPaused: GenericPalletError;

    /**
     * The error happens when bridging message sent with too big payload.
     **/
    MaxPayloadSizeExceeded: GenericPalletError;

    /**
     * The error happens when bridging thorough builtin and message value
     * is inapplicable to operation or insufficient.
     **/
    InsufficientValueApplied: GenericPalletError;

    /**
     * The error happens when attempted to reset overflowed queue, but
     * queue isn't overflowed or incorrect finality proof provided.
     **/
    InvalidQueueReset: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
  /**
   * Pallet `GrandpaSigner`'s errors
   **/
  grandpaSigner: {
    TooManyRequests: GenericPalletError;
    RequestIdExhausted: GenericPalletError;
    UnknownRequest: GenericPalletError;
    RequestExpired: GenericPalletError;
    AuthorityNotInSet: GenericPalletError;
    AlreadySigned: GenericPalletError;
    BadSignature: GenericPalletError;
    UnsupportedSet: GenericPalletError;
    PayloadTooLong: GenericPalletError;
    MaxSignaturesReached: GenericPalletError;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError;
  };
}
