// Generated by dedot cli

import type { GenericSubstrateApi, GenericChainKnownTypes, RpcLegacy, RpcV2, RpcVersion } from 'dedot/types';
import type { MultiAddress } from 'dedot/codecs';
import type {
  VaraRuntimeRuntimeCall,
  SpRuntimeMultiSignature,
  PalletGearStakingRewardsExtensionStakingBlackList,
  FrameSystemExtensionsCheckNonZeroSender,
  FrameSystemExtensionsCheckSpecVersion,
  FrameSystemExtensionsCheckTxVersion,
  FrameSystemExtensionsCheckGenesis,
  FrameSystemExtensionsCheckMortality,
  VaraRuntimeCustomCheckNonce,
  FrameSystemExtensionsCheckWeight,
  PalletGearPaymentCustomChargeTransactionPayment,
  FrameMetadataHashExtensionCheckMetadataHash,
} from './types.js';
import { ChainConsts } from './consts.js';
import { ChainStorage } from './query.js';
import { ChainJsonRpcApis } from './json-rpc.js';
import { ChainErrors } from './errors.js';
import { ChainEvents } from './events.js';
import { RuntimeApis } from './runtime.js';
import { ChainViewFunctions } from './view-functions.js';
import { ChainTx } from './tx.js';

export * from './types.js';

interface ChainKnownTypes extends GenericChainKnownTypes {
  Address: MultiAddress;
  Signature: SpRuntimeMultiSignature;
  RuntimeCall: VaraRuntimeRuntimeCall;
  Extra: [
    PalletGearStakingRewardsExtensionStakingBlackList,
    FrameSystemExtensionsCheckNonZeroSender,
    FrameSystemExtensionsCheckSpecVersion,
    FrameSystemExtensionsCheckTxVersion,
    FrameSystemExtensionsCheckGenesis,
    FrameSystemExtensionsCheckMortality,
    VaraRuntimeCustomCheckNonce,
    FrameSystemExtensionsCheckWeight,
    PalletGearPaymentCustomChargeTransactionPayment,
    FrameMetadataHashExtensionCheckMetadataHash,
  ];
}

export interface VersionedVaraApi<Rv extends RpcVersion> extends GenericSubstrateApi<Rv> {
  rpc: ChainJsonRpcApis<Rv>;
  consts: ChainConsts<Rv>;
  query: ChainStorage<Rv>;
  errors: ChainErrors<Rv>;
  events: ChainEvents<Rv>;
  call: RuntimeApis<Rv>;
  view: ChainViewFunctions<Rv>;
  tx: ChainTx<Rv>;

  types: ChainKnownTypes;
}

/**
 * @name: VaraApi
 * @specVersion: 1910
 **/
export interface VaraApi {
  legacy: VersionedVaraApi<RpcLegacy>;
  v2: VersionedVaraApi<RpcV2>;
}
