// Generated by dedot cli

import type { GenericChainErrors, GenericPalletError, RpcVersion } from 'dedot/types';

export interface ChainErrors<Rv extends RpcVersion> extends GenericChainErrors<Rv> {
  /**
   * Pallet `System`'s errors
   **/
  system: {
    /**
     * The name of specification does not match between the current runtime
     * and the new runtime.
     **/
    InvalidSpecName: GenericPalletError<Rv>;

    /**
     * The specification version is not allowed to decrease between the current runtime
     * and the new runtime.
     **/
    SpecVersionNeedsToIncrease: GenericPalletError<Rv>;

    /**
     * Failed to extract the runtime version from the new runtime.
     *
     * Either calling `Core_version` or decoding `RuntimeVersion` failed.
     **/
    FailedToExtractRuntimeVersion: GenericPalletError<Rv>;

    /**
     * Suicide called when the account has non-default composite data.
     **/
    NonDefaultComposite: GenericPalletError<Rv>;

    /**
     * There is a non-zero reference count preventing the account from being purged.
     **/
    NonZeroRefCount: GenericPalletError<Rv>;

    /**
     * The origin filter prevent the call to be dispatched.
     **/
    CallFiltered: GenericPalletError<Rv>;

    /**
     * A multi-block migration is ongoing and prevents the current code from being replaced.
     **/
    MultiBlockMigrationsOngoing: GenericPalletError<Rv>;

    /**
     * No upgrade authorized.
     **/
    NothingAuthorized: GenericPalletError<Rv>;

    /**
     * The submitted code is not authorized.
     **/
    Unauthorized: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Balances`'s errors
   **/
  balances: {
    /**
     * Vesting balance too high to send value.
     **/
    VestingBalance: GenericPalletError<Rv>;

    /**
     * Account liquidity restrictions prevent withdrawal.
     **/
    LiquidityRestrictions: GenericPalletError<Rv>;

    /**
     * Balance too low to send value.
     **/
    InsufficientBalance: GenericPalletError<Rv>;

    /**
     * Value too low to create account due to existential deposit.
     **/
    ExistentialDeposit: GenericPalletError<Rv>;

    /**
     * Transfer/payment would kill account.
     **/
    Expendability: GenericPalletError<Rv>;

    /**
     * A vesting schedule already exists for this account.
     **/
    ExistingVestingSchedule: GenericPalletError<Rv>;

    /**
     * Beneficiary account must pre-exist.
     **/
    DeadAccount: GenericPalletError<Rv>;

    /**
     * Number of named reserves exceed `MaxReserves`.
     **/
    TooManyReserves: GenericPalletError<Rv>;

    /**
     * Number of holds exceed `VariantCountOf<T::RuntimeHoldReason>`.
     **/
    TooManyHolds: GenericPalletError<Rv>;

    /**
     * Number of freezes exceed `MaxFreezes`.
     **/
    TooManyFreezes: GenericPalletError<Rv>;

    /**
     * The issuance cannot be modified since it is already deactivated.
     **/
    IssuanceDeactivated: GenericPalletError<Rv>;

    /**
     * The delta cannot be zero.
     **/
    DeltaZero: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `MultiTransactionPayment`'s errors
   **/
  multiTransactionPayment: {
    /**
     * Selected currency is not supported.
     **/
    UnsupportedCurrency: GenericPalletError<Rv>;

    /**
     * Account balance should be non-zero.
     **/
    ZeroBalance: GenericPalletError<Rv>;

    /**
     * Currency is already in the list of accepted currencies.
     **/
    AlreadyAccepted: GenericPalletError<Rv>;

    /**
     * It is not allowed to add Core Asset as accepted currency. Core asset is accepted by design.
     **/
    CoreAssetNotAllowed: GenericPalletError<Rv>;

    /**
     * Fallback price cannot be zero.
     **/
    ZeroPrice: GenericPalletError<Rv>;

    /**
     * Fallback price was not found.
     **/
    FallbackPriceNotFound: GenericPalletError<Rv>;

    /**
     * Math overflow
     **/
    Overflow: GenericPalletError<Rv>;

    /**
     * It is not allowed to change payment currency of an EVM account.
     **/
    EvmAccountNotAllowed: GenericPalletError<Rv>;

    /**
     * EVM permit expired.
     **/
    EvmPermitExpired: GenericPalletError<Rv>;

    /**
     * EVM permit is invalid.
     **/
    EvmPermitInvalid: GenericPalletError<Rv>;

    /**
     * EVM permit call failed.
     **/
    EvmPermitCallExecutionError: GenericPalletError<Rv>;

    /**
     * EVM permit call failed.
     **/
    EvmPermitRunnerError: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Treasury`'s errors
   **/
  treasury: {
    /**
     * No proposal, bounty or spend at that index.
     **/
    InvalidIndex: GenericPalletError<Rv>;

    /**
     * Too many approvals in the queue.
     **/
    TooManyApprovals: GenericPalletError<Rv>;

    /**
     * The spend origin is valid but the amount it is allowed to spend is lower than the
     * amount to be spent.
     **/
    InsufficientPermission: GenericPalletError<Rv>;

    /**
     * Proposal has not been approved.
     **/
    ProposalNotApproved: GenericPalletError<Rv>;

    /**
     * The balance of the asset kind is not convertible to the balance of the native asset.
     **/
    FailedToConvertBalance: GenericPalletError<Rv>;

    /**
     * The spend has expired and cannot be claimed.
     **/
    SpendExpired: GenericPalletError<Rv>;

    /**
     * The spend is not yet eligible for payout.
     **/
    EarlyPayout: GenericPalletError<Rv>;

    /**
     * The payment has already been attempted.
     **/
    AlreadyAttempted: GenericPalletError<Rv>;

    /**
     * There was some issue with the mechanism of payment.
     **/
    PayoutError: GenericPalletError<Rv>;

    /**
     * The payout was not yet attempted/claimed.
     **/
    NotAttempted: GenericPalletError<Rv>;

    /**
     * The payment has neither failed nor succeeded yet.
     **/
    Inconclusive: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Utility`'s errors
   **/
  utility: {
    /**
     * Too many calls batched.
     **/
    TooManyCalls: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Democracy`'s errors
   **/
  democracy: {
    /**
     * Value too low
     **/
    ValueLow: GenericPalletError<Rv>;

    /**
     * Proposal does not exist
     **/
    ProposalMissing: GenericPalletError<Rv>;

    /**
     * Cannot cancel the same proposal twice
     **/
    AlreadyCanceled: GenericPalletError<Rv>;

    /**
     * Proposal already made
     **/
    DuplicateProposal: GenericPalletError<Rv>;

    /**
     * Proposal still blacklisted
     **/
    ProposalBlacklisted: GenericPalletError<Rv>;

    /**
     * Next external proposal not simple majority
     **/
    NotSimpleMajority: GenericPalletError<Rv>;

    /**
     * Invalid hash
     **/
    InvalidHash: GenericPalletError<Rv>;

    /**
     * No external proposal
     **/
    NoProposal: GenericPalletError<Rv>;

    /**
     * Identity may not veto a proposal twice
     **/
    AlreadyVetoed: GenericPalletError<Rv>;

    /**
     * Vote given for invalid referendum
     **/
    ReferendumInvalid: GenericPalletError<Rv>;

    /**
     * No proposals waiting
     **/
    NoneWaiting: GenericPalletError<Rv>;

    /**
     * The given account did not vote on the referendum.
     **/
    NotVoter: GenericPalletError<Rv>;

    /**
     * The actor has no permission to conduct the action.
     **/
    NoPermission: GenericPalletError<Rv>;

    /**
     * The account is already delegating.
     **/
    AlreadyDelegating: GenericPalletError<Rv>;

    /**
     * Too high a balance was provided that the account cannot afford.
     **/
    InsufficientFunds: GenericPalletError<Rv>;

    /**
     * The account is not currently delegating.
     **/
    NotDelegating: GenericPalletError<Rv>;

    /**
     * The account currently has votes attached to it and the operation cannot succeed until
     * these are removed, either through `unvote` or `reap_vote`.
     **/
    VotesExist: GenericPalletError<Rv>;

    /**
     * The instant referendum origin is currently disallowed.
     **/
    InstantNotAllowed: GenericPalletError<Rv>;

    /**
     * Delegation to oneself makes no sense.
     **/
    Nonsense: GenericPalletError<Rv>;

    /**
     * Invalid upper bound.
     **/
    WrongUpperBound: GenericPalletError<Rv>;

    /**
     * Maximum number of votes reached.
     **/
    MaxVotesReached: GenericPalletError<Rv>;

    /**
     * Maximum number of items reached.
     **/
    TooMany: GenericPalletError<Rv>;

    /**
     * Voting period too low
     **/
    VotingPeriodLow: GenericPalletError<Rv>;

    /**
     * The preimage does not exist.
     **/
    PreimageNotExist: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `TechnicalCommittee`'s errors
   **/
  technicalCommittee: {
    /**
     * Account is not a member
     **/
    NotMember: GenericPalletError<Rv>;

    /**
     * Duplicate proposals not allowed
     **/
    DuplicateProposal: GenericPalletError<Rv>;

    /**
     * Proposal must exist
     **/
    ProposalMissing: GenericPalletError<Rv>;

    /**
     * Mismatched index
     **/
    WrongIndex: GenericPalletError<Rv>;

    /**
     * Duplicate vote ignored
     **/
    DuplicateVote: GenericPalletError<Rv>;

    /**
     * Members are already initialized!
     **/
    AlreadyInitialized: GenericPalletError<Rv>;

    /**
     * The close call was made too early, before the end of the voting.
     **/
    TooEarly: GenericPalletError<Rv>;

    /**
     * There can only be a maximum of `MaxProposals` active proposals.
     **/
    TooManyProposals: GenericPalletError<Rv>;

    /**
     * The given weight bound for the proposal was too low.
     **/
    WrongProposalWeight: GenericPalletError<Rv>;

    /**
     * The given length bound for the proposal was too low.
     **/
    WrongProposalLength: GenericPalletError<Rv>;

    /**
     * Prime account is not a member
     **/
    PrimeAccountNotMember: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Vesting`'s errors
   **/
  vesting: {
    /**
     * Vesting period is zero
     **/
    ZeroVestingPeriod: GenericPalletError<Rv>;

    /**
     * Number of vests is zero
     **/
    ZeroVestingPeriodCount: GenericPalletError<Rv>;

    /**
     * Insufficient amount of balance to lock
     **/
    InsufficientBalanceToLock: GenericPalletError<Rv>;

    /**
     * This account have too many vesting schedules
     **/
    TooManyVestingSchedules: GenericPalletError<Rv>;

    /**
     * The vested transfer amount is too low
     **/
    AmountLow: GenericPalletError<Rv>;

    /**
     * Failed because the maximum vesting schedules was exceeded
     **/
    MaxVestingSchedulesExceeded: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Proxy`'s errors
   **/
  proxy: {
    /**
     * There are too many proxies registered or too many announcements pending.
     **/
    TooMany: GenericPalletError<Rv>;

    /**
     * Proxy registration not found.
     **/
    NotFound: GenericPalletError<Rv>;

    /**
     * Sender is not a proxy of the account to be proxied.
     **/
    NotProxy: GenericPalletError<Rv>;

    /**
     * A call which is incompatible with the proxy type's filter was attempted.
     **/
    Unproxyable: GenericPalletError<Rv>;

    /**
     * Account is already a proxy.
     **/
    Duplicate: GenericPalletError<Rv>;

    /**
     * Call may not be made by proxy because it may escalate its privileges.
     **/
    NoPermission: GenericPalletError<Rv>;

    /**
     * Announcement, if made at all, was made too recently.
     **/
    Unannounced: GenericPalletError<Rv>;

    /**
     * Cannot add self as proxy.
     **/
    NoSelfProxy: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `CollatorSelection`'s errors
   **/
  collatorSelection: {
    /**
     * The pallet has too many candidates.
     **/
    TooManyCandidates: GenericPalletError<Rv>;

    /**
     * Leaving would result in too few candidates.
     **/
    TooFewEligibleCollators: GenericPalletError<Rv>;

    /**
     * Account is already a candidate.
     **/
    AlreadyCandidate: GenericPalletError<Rv>;

    /**
     * Account is not a candidate.
     **/
    NotCandidate: GenericPalletError<Rv>;

    /**
     * There are too many Invulnerables.
     **/
    TooManyInvulnerables: GenericPalletError<Rv>;

    /**
     * Account is already an Invulnerable.
     **/
    AlreadyInvulnerable: GenericPalletError<Rv>;

    /**
     * Account is not an Invulnerable.
     **/
    NotInvulnerable: GenericPalletError<Rv>;

    /**
     * Account has no associated validator ID.
     **/
    NoAssociatedValidatorId: GenericPalletError<Rv>;

    /**
     * Validator ID is not yet registered.
     **/
    ValidatorNotRegistered: GenericPalletError<Rv>;

    /**
     * Could not insert in the candidate list.
     **/
    InsertToCandidateListFailed: GenericPalletError<Rv>;

    /**
     * Could not remove from the candidate list.
     **/
    RemoveFromCandidateListFailed: GenericPalletError<Rv>;

    /**
     * New deposit amount would be below the minimum candidacy bond.
     **/
    DepositTooLow: GenericPalletError<Rv>;

    /**
     * Could not update the candidate list.
     **/
    UpdateCandidateListFailed: GenericPalletError<Rv>;

    /**
     * Deposit amount is too low to take the target's slot in the candidate list.
     **/
    InsufficientBond: GenericPalletError<Rv>;

    /**
     * The target account to be replaced in the candidate list is not a candidate.
     **/
    TargetIsNotCandidate: GenericPalletError<Rv>;

    /**
     * The updated deposit amount is equal to the amount already reserved.
     **/
    IdenticalDeposit: GenericPalletError<Rv>;

    /**
     * Cannot lower candidacy bond while occupying a future collator slot in the list.
     **/
    InvalidUnreserve: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Session`'s errors
   **/
  session: {
    /**
     * Invalid ownership proof.
     **/
    InvalidProof: GenericPalletError<Rv>;

    /**
     * No associated validator ID for account.
     **/
    NoAssociatedValidatorId: GenericPalletError<Rv>;

    /**
     * Registered duplicate key.
     **/
    DuplicatedKey: GenericPalletError<Rv>;

    /**
     * No keys are associated with this account.
     **/
    NoKeys: GenericPalletError<Rv>;

    /**
     * Key setting account is not live, so it's impossible to associate keys.
     **/
    NoAccount: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Preimage`'s errors
   **/
  preimage: {
    /**
     * Preimage is too large to store on-chain.
     **/
    TooBig: GenericPalletError<Rv>;

    /**
     * Preimage has already been noted on-chain.
     **/
    AlreadyNoted: GenericPalletError<Rv>;

    /**
     * The user is not authorized to perform this action.
     **/
    NotAuthorized: GenericPalletError<Rv>;

    /**
     * The preimage cannot be removed since it has not yet been noted.
     **/
    NotNoted: GenericPalletError<Rv>;

    /**
     * A preimage may not be removed when there are outstanding requests.
     **/
    Requested: GenericPalletError<Rv>;

    /**
     * The preimage request cannot be removed since no outstanding requests exist.
     **/
    NotRequested: GenericPalletError<Rv>;

    /**
     * More than `MAX_HASH_UPGRADE_BULK_COUNT` hashes were requested to be upgraded at once.
     **/
    TooMany: GenericPalletError<Rv>;

    /**
     * Too few hashes were requested to be upgraded (i.e. zero).
     **/
    TooFew: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Uniques`'s errors
   **/
  uniques: {
    /**
     * The signing account has no permission to do the operation.
     **/
    NoPermission: GenericPalletError<Rv>;

    /**
     * The given item ID is unknown.
     **/
    UnknownCollection: GenericPalletError<Rv>;

    /**
     * The item ID has already been used for an item.
     **/
    AlreadyExists: GenericPalletError<Rv>;

    /**
     * The owner turned out to be different to what was expected.
     **/
    WrongOwner: GenericPalletError<Rv>;

    /**
     * Invalid witness data given.
     **/
    BadWitness: GenericPalletError<Rv>;

    /**
     * The item ID is already taken.
     **/
    InUse: GenericPalletError<Rv>;

    /**
     * The item or collection is frozen.
     **/
    Frozen: GenericPalletError<Rv>;

    /**
     * The delegate turned out to be different to what was expected.
     **/
    WrongDelegate: GenericPalletError<Rv>;

    /**
     * There is no delegate approved.
     **/
    NoDelegate: GenericPalletError<Rv>;

    /**
     * No approval exists that would allow the transfer.
     **/
    Unapproved: GenericPalletError<Rv>;

    /**
     * The named owner has not signed ownership of the collection is acceptable.
     **/
    Unaccepted: GenericPalletError<Rv>;

    /**
     * The item is locked.
     **/
    Locked: GenericPalletError<Rv>;

    /**
     * All items have been minted.
     **/
    MaxSupplyReached: GenericPalletError<Rv>;

    /**
     * The max supply has already been set.
     **/
    MaxSupplyAlreadySet: GenericPalletError<Rv>;

    /**
     * The provided max supply is less to the amount of items a collection already has.
     **/
    MaxSupplyTooSmall: GenericPalletError<Rv>;

    /**
     * The given item ID is unknown.
     **/
    UnknownItem: GenericPalletError<Rv>;

    /**
     * Item is not for sale.
     **/
    NotForSale: GenericPalletError<Rv>;

    /**
     * The provided bid is too low.
     **/
    BidTooLow: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Identity`'s errors
   **/
  identity: {
    /**
     * Too many subs-accounts.
     **/
    TooManySubAccounts: GenericPalletError<Rv>;

    /**
     * Account isn't found.
     **/
    NotFound: GenericPalletError<Rv>;

    /**
     * Account isn't named.
     **/
    NotNamed: GenericPalletError<Rv>;

    /**
     * Empty index.
     **/
    EmptyIndex: GenericPalletError<Rv>;

    /**
     * Fee is changed.
     **/
    FeeChanged: GenericPalletError<Rv>;

    /**
     * No identity found.
     **/
    NoIdentity: GenericPalletError<Rv>;

    /**
     * Sticky judgement.
     **/
    StickyJudgement: GenericPalletError<Rv>;

    /**
     * Judgement given.
     **/
    JudgementGiven: GenericPalletError<Rv>;

    /**
     * Invalid judgement.
     **/
    InvalidJudgement: GenericPalletError<Rv>;

    /**
     * The index is invalid.
     **/
    InvalidIndex: GenericPalletError<Rv>;

    /**
     * The target is invalid.
     **/
    InvalidTarget: GenericPalletError<Rv>;

    /**
     * Maximum amount of registrars reached. Cannot add any more.
     **/
    TooManyRegistrars: GenericPalletError<Rv>;

    /**
     * Account ID is already named.
     **/
    AlreadyClaimed: GenericPalletError<Rv>;

    /**
     * Sender is not a sub-account.
     **/
    NotSub: GenericPalletError<Rv>;

    /**
     * Sub-account isn't owned by sender.
     **/
    NotOwned: GenericPalletError<Rv>;

    /**
     * The provided judgement was for a different identity.
     **/
    JudgementForDifferentIdentity: GenericPalletError<Rv>;

    /**
     * Error that occurs when there is an issue paying for judgement.
     **/
    JudgementPaymentFailed: GenericPalletError<Rv>;

    /**
     * The provided suffix is too long.
     **/
    InvalidSuffix: GenericPalletError<Rv>;

    /**
     * The sender does not have permission to issue a username.
     **/
    NotUsernameAuthority: GenericPalletError<Rv>;

    /**
     * The authority cannot allocate any more usernames.
     **/
    NoAllocation: GenericPalletError<Rv>;

    /**
     * The signature on a username was not valid.
     **/
    InvalidSignature: GenericPalletError<Rv>;

    /**
     * Setting this username requires a signature, but none was provided.
     **/
    RequiresSignature: GenericPalletError<Rv>;

    /**
     * The username does not meet the requirements.
     **/
    InvalidUsername: GenericPalletError<Rv>;

    /**
     * The username is already taken.
     **/
    UsernameTaken: GenericPalletError<Rv>;

    /**
     * The requested username does not exist.
     **/
    NoUsername: GenericPalletError<Rv>;

    /**
     * The username cannot be forcefully removed because it can still be accepted.
     **/
    NotExpired: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Multisig`'s errors
   **/
  multisig: {
    /**
     * Threshold must be 2 or greater.
     **/
    MinimumThreshold: GenericPalletError<Rv>;

    /**
     * Call is already approved by this signatory.
     **/
    AlreadyApproved: GenericPalletError<Rv>;

    /**
     * Call doesn't need any (more) approvals.
     **/
    NoApprovalsNeeded: GenericPalletError<Rv>;

    /**
     * There are too few signatories in the list.
     **/
    TooFewSignatories: GenericPalletError<Rv>;

    /**
     * There are too many signatories in the list.
     **/
    TooManySignatories: GenericPalletError<Rv>;

    /**
     * The signatories were provided out of order; they should be ordered.
     **/
    SignatoriesOutOfOrder: GenericPalletError<Rv>;

    /**
     * The sender was contained in the other signatories; it shouldn't be.
     **/
    SenderInSignatories: GenericPalletError<Rv>;

    /**
     * Multisig operation not found when attempting to cancel.
     **/
    NotFound: GenericPalletError<Rv>;

    /**
     * Only the account that originally created the multisig is able to cancel it.
     **/
    NotOwner: GenericPalletError<Rv>;

    /**
     * No timepoint was given, yet the multisig operation is already underway.
     **/
    NoTimepoint: GenericPalletError<Rv>;

    /**
     * A different timepoint was given to the multisig operation that is underway.
     **/
    WrongTimepoint: GenericPalletError<Rv>;

    /**
     * A timepoint was given, yet no multisig operation is underway.
     **/
    UnexpectedTimepoint: GenericPalletError<Rv>;

    /**
     * The maximum weight information provided was too low.
     **/
    MaxWeightTooLow: GenericPalletError<Rv>;

    /**
     * The data to be stored is already stored.
     **/
    AlreadyStored: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `StateTrieMigration`'s errors
   **/
  stateTrieMigration: {
    /**
     * Max signed limits not respected.
     **/
    MaxSignedLimits: GenericPalletError<Rv>;

    /**
     * A key was longer than the configured maximum.
     *
     * This means that the migration halted at the current [`Progress`] and
     * can be resumed with a larger [`crate::Config::MaxKeyLen`] value.
     * Retrying with the same [`crate::Config::MaxKeyLen`] value will not work.
     * The value should only be increased to avoid a storage migration for the currently
     * stored [`crate::Progress::LastKey`].
     **/
    KeyTooLong: GenericPalletError<Rv>;

    /**
     * submitter does not have enough funds.
     **/
    NotEnoughFunds: GenericPalletError<Rv>;

    /**
     * Bad witness data provided.
     **/
    BadWitness: GenericPalletError<Rv>;

    /**
     * Signed migration is not allowed because the maximum limit is not set yet.
     **/
    SignedMigrationNotAllowed: GenericPalletError<Rv>;

    /**
     * Bad child root provided.
     **/
    BadChildRoot: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `ConvictionVoting`'s errors
   **/
  convictionVoting: {
    /**
     * Poll is not ongoing.
     **/
    NotOngoing: GenericPalletError<Rv>;

    /**
     * The given account did not vote on the poll.
     **/
    NotVoter: GenericPalletError<Rv>;

    /**
     * The actor has no permission to conduct the action.
     **/
    NoPermission: GenericPalletError<Rv>;

    /**
     * The actor has no permission to conduct the action right now but will do in the future.
     **/
    NoPermissionYet: GenericPalletError<Rv>;

    /**
     * The account is already delegating.
     **/
    AlreadyDelegating: GenericPalletError<Rv>;

    /**
     * The account currently has votes attached to it and the operation cannot succeed until
     * these are removed through `remove_vote`.
     **/
    AlreadyVoting: GenericPalletError<Rv>;

    /**
     * Too high a balance was provided that the account cannot afford.
     **/
    InsufficientFunds: GenericPalletError<Rv>;

    /**
     * The account is not currently delegating.
     **/
    NotDelegating: GenericPalletError<Rv>;

    /**
     * Delegation to oneself makes no sense.
     **/
    Nonsense: GenericPalletError<Rv>;

    /**
     * Maximum number of votes reached.
     **/
    MaxVotesReached: GenericPalletError<Rv>;

    /**
     * The class must be supplied since it is not easily determinable from the state.
     **/
    ClassNeeded: GenericPalletError<Rv>;

    /**
     * The class ID supplied is invalid.
     **/
    BadClass: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Referenda`'s errors
   **/
  referenda: {
    /**
     * Referendum is not ongoing.
     **/
    NotOngoing: GenericPalletError<Rv>;

    /**
     * Referendum's decision deposit is already paid.
     **/
    HasDeposit: GenericPalletError<Rv>;

    /**
     * The track identifier given was invalid.
     **/
    BadTrack: GenericPalletError<Rv>;

    /**
     * There are already a full complement of referenda in progress for this track.
     **/
    Full: GenericPalletError<Rv>;

    /**
     * The queue of the track is empty.
     **/
    QueueEmpty: GenericPalletError<Rv>;

    /**
     * The referendum index provided is invalid in this context.
     **/
    BadReferendum: GenericPalletError<Rv>;

    /**
     * There was nothing to do in the advancement.
     **/
    NothingToDo: GenericPalletError<Rv>;

    /**
     * No track exists for the proposal origin.
     **/
    NoTrack: GenericPalletError<Rv>;

    /**
     * Any deposit cannot be refunded until after the decision is over.
     **/
    Unfinished: GenericPalletError<Rv>;

    /**
     * The deposit refunder is not the depositor.
     **/
    NoPermission: GenericPalletError<Rv>;

    /**
     * The deposit cannot be refunded since none was made.
     **/
    NoDeposit: GenericPalletError<Rv>;

    /**
     * The referendum status is invalid for this operation.
     **/
    BadStatus: GenericPalletError<Rv>;

    /**
     * The preimage does not exist.
     **/
    PreimageNotExist: GenericPalletError<Rv>;

    /**
     * The preimage is stored with a different length than the one provided.
     **/
    PreimageStoredWithDifferentLength: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Whitelist`'s errors
   **/
  whitelist: {
    /**
     * The preimage of the call hash could not be loaded.
     **/
    UnavailablePreImage: GenericPalletError<Rv>;

    /**
     * The call could not be decoded.
     **/
    UndecodableCall: GenericPalletError<Rv>;

    /**
     * The weight of the decoded call was higher than the witness.
     **/
    InvalidCallWeightWitness: GenericPalletError<Rv>;

    /**
     * The call was not whitelisted.
     **/
    CallIsNotWhitelisted: GenericPalletError<Rv>;

    /**
     * The call was already whitelisted; No-Op.
     **/
    CallAlreadyWhitelisted: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `RelayChainInfo`'s errors
   **/
  relayChainInfo: {
    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Scheduler`'s errors
   **/
  scheduler: {
    /**
     * Failed to schedule a call
     **/
    FailedToSchedule: GenericPalletError<Rv>;

    /**
     * Cannot find the scheduled call.
     **/
    NotFound: GenericPalletError<Rv>;

    /**
     * Given target block number is in the past.
     **/
    TargetBlockNumberInPast: GenericPalletError<Rv>;

    /**
     * Reschedule failed because it does not change scheduled time.
     **/
    RescheduleNoChange: GenericPalletError<Rv>;

    /**
     * Attempt to use a non-named function on a named task.
     **/
    Named: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `ParachainSystem`'s errors
   **/
  parachainSystem: {
    /**
     * Attempt to upgrade validation function while existing upgrade pending.
     **/
    OverlappingUpgrades: GenericPalletError<Rv>;

    /**
     * Polkadot currently prohibits this parachain from upgrading its validation function.
     **/
    ProhibitedByPolkadot: GenericPalletError<Rv>;

    /**
     * The supplied validation function has compiled into a blob larger than Polkadot is
     * willing to run.
     **/
    TooBig: GenericPalletError<Rv>;

    /**
     * The inherent which supplies the validation data did not run this block.
     **/
    ValidationDataNotAvailable: GenericPalletError<Rv>;

    /**
     * The inherent which supplies the host configuration did not run this block.
     **/
    HostConfigurationNotAvailable: GenericPalletError<Rv>;

    /**
     * No validation function upgrade is currently scheduled.
     **/
    NotScheduled: GenericPalletError<Rv>;

    /**
     * No code upgrade has been authorized.
     **/
    NothingAuthorized: GenericPalletError<Rv>;

    /**
     * The given code upgrade has not been authorized.
     **/
    Unauthorized: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `PolkadotXcm`'s errors
   **/
  polkadotXcm: {
    /**
     * The desired destination was unreachable, generally because there is a no way of routing
     * to it.
     **/
    Unreachable: GenericPalletError<Rv>;

    /**
     * There was some other issue (i.e. not to do with routing) in sending the message.
     * Perhaps a lack of space for buffering the message.
     **/
    SendFailure: GenericPalletError<Rv>;

    /**
     * The message execution fails the filter.
     **/
    Filtered: GenericPalletError<Rv>;

    /**
     * The message's weight could not be determined.
     **/
    UnweighableMessage: GenericPalletError<Rv>;

    /**
     * The destination `Location` provided cannot be inverted.
     **/
    DestinationNotInvertible: GenericPalletError<Rv>;

    /**
     * The assets to be sent are empty.
     **/
    Empty: GenericPalletError<Rv>;

    /**
     * Could not re-anchor the assets to declare the fees for the destination chain.
     **/
    CannotReanchor: GenericPalletError<Rv>;

    /**
     * Too many assets have been attempted for transfer.
     **/
    TooManyAssets: GenericPalletError<Rv>;

    /**
     * Origin is invalid for sending.
     **/
    InvalidOrigin: GenericPalletError<Rv>;

    /**
     * The version of the `Versioned` value used is not able to be interpreted.
     **/
    BadVersion: GenericPalletError<Rv>;

    /**
     * The given location could not be used (e.g. because it cannot be expressed in the
     * desired version of XCM).
     **/
    BadLocation: GenericPalletError<Rv>;

    /**
     * The referenced subscription could not be found.
     **/
    NoSubscription: GenericPalletError<Rv>;

    /**
     * The location is invalid since it already has a subscription from us.
     **/
    AlreadySubscribed: GenericPalletError<Rv>;

    /**
     * Could not check-out the assets for teleportation to the destination chain.
     **/
    CannotCheckOutTeleport: GenericPalletError<Rv>;

    /**
     * The owner does not own (all) of the asset that they wish to do the operation on.
     **/
    LowBalance: GenericPalletError<Rv>;

    /**
     * The asset owner has too many locks on the asset.
     **/
    TooManyLocks: GenericPalletError<Rv>;

    /**
     * The given account is not an identifiable sovereign account for any location.
     **/
    AccountNotSovereign: GenericPalletError<Rv>;

    /**
     * The operation required fees to be paid which the initiator could not meet.
     **/
    FeesNotMet: GenericPalletError<Rv>;

    /**
     * A remote lock with the corresponding data could not be found.
     **/
    LockNotFound: GenericPalletError<Rv>;

    /**
     * The unlock operation cannot succeed because there are still consumers of the lock.
     **/
    InUse: GenericPalletError<Rv>;

    /**
     * Invalid asset, reserve chain could not be determined for it.
     **/
    InvalidAssetUnknownReserve: GenericPalletError<Rv>;

    /**
     * Invalid asset, do not support remote asset reserves with different fees reserves.
     **/
    InvalidAssetUnsupportedReserve: GenericPalletError<Rv>;

    /**
     * Too many assets with different reserve locations have been attempted for transfer.
     **/
    TooManyReserves: GenericPalletError<Rv>;

    /**
     * Local XCM execution incomplete.
     **/
    LocalExecutionIncomplete: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `XcmpQueue`'s errors
   **/
  xcmpQueue: {
    /**
     * Setting the queue config failed since one of its values was invalid.
     **/
    BadQueueConfig: GenericPalletError<Rv>;

    /**
     * The execution is already suspended.
     **/
    AlreadySuspended: GenericPalletError<Rv>;

    /**
     * The execution is already resumed.
     **/
    AlreadyResumed: GenericPalletError<Rv>;

    /**
     * There are too many active outbound channels.
     **/
    TooManyActiveOutboundChannels: GenericPalletError<Rv>;

    /**
     * The message is too big.
     **/
    TooBig: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `MessageQueue`'s errors
   **/
  messageQueue: {
    /**
     * Page is not reapable because it has items remaining to be processed and is not old
     * enough.
     **/
    NotReapable: GenericPalletError<Rv>;

    /**
     * Page to be reaped does not exist.
     **/
    NoPage: GenericPalletError<Rv>;

    /**
     * The referenced message could not be found.
     **/
    NoMessage: GenericPalletError<Rv>;

    /**
     * The message was already processed and cannot be processed again.
     **/
    AlreadyProcessed: GenericPalletError<Rv>;

    /**
     * The message is queued for future execution.
     **/
    Queued: GenericPalletError<Rv>;

    /**
     * There is temporarily not enough weight to continue servicing messages.
     **/
    InsufficientWeight: GenericPalletError<Rv>;

    /**
     * This message is temporarily unprocessable.
     *
     * Such errors are expected, but not guaranteed, to resolve themselves eventually through
     * retrying.
     **/
    TemporarilyUnprocessable: GenericPalletError<Rv>;

    /**
     * The queue is paused and no message can be executed from it.
     *
     * This can change at any time and may resolve in the future by re-trying.
     **/
    QueuePaused: GenericPalletError<Rv>;

    /**
     * Another call is in progress and needs to finish before this call can happen.
     **/
    RecursiveDisallowed: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `AssetRegistry`'s errors
   **/
  assetRegistry: {
    /**
     * Asset ID is not available. This only happens when it reaches the MAX value of given id type.
     **/
    NoIdAvailable: GenericPalletError<Rv>;

    /**
     * Invalid asset name or symbol.
     **/
    AssetNotFound: GenericPalletError<Rv>;

    /**
     * Invalid asset name or symbol.
     **/
    TooLong: GenericPalletError<Rv>;

    /**
     * Asset ID is not registered in the asset-registry.
     **/
    AssetNotRegistered: GenericPalletError<Rv>;

    /**
     * Asset is already registered.
     **/
    AssetAlreadyRegistered: GenericPalletError<Rv>;

    /**
     * Incorrect number of assets provided to create shared asset.
     **/
    InvalidSharedAssetLen: GenericPalletError<Rv>;

    /**
     * Cannot update asset location
     **/
    CannotUpdateLocation: GenericPalletError<Rv>;

    /**
     * Selected asset id is out of reserved range.
     **/
    NotInReservedRange: GenericPalletError<Rv>;

    /**
     * Location already registered with different asset
     **/
    LocationAlreadyRegistered: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `XYK`'s errors
   **/
  xyk: {
    /**
     * It is not allowed to create a pool between same assets.
     **/
    CannotCreatePoolWithSameAssets: GenericPalletError<Rv>;

    /**
     * Liquidity has not reached the required minimum.
     **/
    InsufficientLiquidity: GenericPalletError<Rv>;

    /**
     * Amount is less than min trading limit.
     **/
    InsufficientTradingAmount: GenericPalletError<Rv>;

    /**
     * Liquidity is zero.
     **/
    ZeroLiquidity: GenericPalletError<Rv>;

    /**
     * It is not allowed to create a pool with zero initial price.
     * Not used, kept for backward compatibility
     **/
    ZeroInitialPrice: GenericPalletError<Rv>;

    /**
     * Overflow
     * Not used, kept for backward compatibility
     **/
    CreatePoolAssetAmountInvalid: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    InvalidMintedLiquidity: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    InvalidLiquidityAmount: GenericPalletError<Rv>;

    /**
     * Asset amount has exceeded given limit.
     **/
    AssetAmountExceededLimit: GenericPalletError<Rv>;

    /**
     * Asset amount has not reached given limit.
     **/
    AssetAmountNotReachedLimit: GenericPalletError<Rv>;

    /**
     * Asset balance is not sufficient.
     **/
    InsufficientAssetBalance: GenericPalletError<Rv>;

    /**
     * Not enough asset liquidity in the pool.
     **/
    InsufficientPoolAssetBalance: GenericPalletError<Rv>;

    /**
     * Not enough core asset liquidity in the pool.
     **/
    InsufficientNativeCurrencyBalance: GenericPalletError<Rv>;

    /**
     * Liquidity pool for given assets does not exist.
     **/
    TokenPoolNotFound: GenericPalletError<Rv>;

    /**
     * Liquidity pool for given assets already exists.
     **/
    TokenPoolAlreadyExists: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    AddAssetAmountInvalid: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    RemoveAssetAmountInvalid: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    SellAssetAmountInvalid: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    BuyAssetAmountInvalid: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    FeeAmountInvalid: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    CannotApplyDiscount: GenericPalletError<Rv>;

    /**
     * Max fraction of pool to buy in single transaction has been exceeded.
     **/
    MaxOutRatioExceeded: GenericPalletError<Rv>;

    /**
     * Max fraction of pool to sell in single transaction has been exceeded.
     **/
    MaxInRatioExceeded: GenericPalletError<Rv>;

    /**
     * Overflow
     **/
    Overflow: GenericPalletError<Rv>;

    /**
     * Pool cannot be created due to outside factors.
     **/
    CannotCreatePool: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Duster`'s errors
   **/
  duster: {
    /**
     * Account is excluded from dusting.
     **/
    AccountBlacklisted: GenericPalletError<Rv>;

    /**
     * Account is not present in the non-dustable list.
     **/
    AccountNotBlacklisted: GenericPalletError<Rv>;

    /**
     * The balance is zero.
     **/
    ZeroBalance: GenericPalletError<Rv>;

    /**
     * The balance is sufficient to keep account open.
     **/
    BalanceSufficient: GenericPalletError<Rv>;

    /**
     * Dust account is not set.
     **/
    DustAccountNotSet: GenericPalletError<Rv>;

    /**
     * Reserve account is not set.
     **/
    ReserveAccountNotSet: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `LBP`'s errors
   **/
  lbp: {
    /**
     * Pool assets can not be the same
     **/
    CannotCreatePoolWithSameAssets: GenericPalletError<Rv>;

    /**
     * Account is not a pool owner
     **/
    NotOwner: GenericPalletError<Rv>;

    /**
     * Sale already started
     **/
    SaleStarted: GenericPalletError<Rv>;

    /**
     * Sale is still in progress
     **/
    SaleNotEnded: GenericPalletError<Rv>;

    /**
     * Sale is not running
     **/
    SaleIsNotRunning: GenericPalletError<Rv>;

    /**
     * Sale duration is too long
     **/
    MaxSaleDurationExceeded: GenericPalletError<Rv>;

    /**
     * Liquidity being added should not be zero
     **/
    CannotAddZeroLiquidity: GenericPalletError<Rv>;

    /**
     * Asset balance too low
     **/
    InsufficientAssetBalance: GenericPalletError<Rv>;

    /**
     * Pool does not exist
     **/
    PoolNotFound: GenericPalletError<Rv>;

    /**
     * Pool has been already created
     **/
    PoolAlreadyExists: GenericPalletError<Rv>;

    /**
     * Invalid block range
     **/
    InvalidBlockRange: GenericPalletError<Rv>;

    /**
     * Calculation error
     **/
    WeightCalculationError: GenericPalletError<Rv>;

    /**
     * Weight set is out of range
     **/
    InvalidWeight: GenericPalletError<Rv>;

    /**
     * Can not perform a trade with zero amount
     **/
    ZeroAmount: GenericPalletError<Rv>;

    /**
     * Trade amount is too high
     **/
    MaxInRatioExceeded: GenericPalletError<Rv>;

    /**
     * Trade amount is too high
     **/
    MaxOutRatioExceeded: GenericPalletError<Rv>;

    /**
     * Invalid fee amount
     **/
    FeeAmountInvalid: GenericPalletError<Rv>;

    /**
     * Trading limit reached
     **/
    TradingLimitReached: GenericPalletError<Rv>;

    /**
     * An unexpected integer overflow occurred
     **/
    Overflow: GenericPalletError<Rv>;

    /**
     * Nothing to update
     **/
    NothingToUpdate: GenericPalletError<Rv>;

    /**
     * Liquidity has not reached the required minimum.
     **/
    InsufficientLiquidity: GenericPalletError<Rv>;

    /**
     * Amount is less than minimum trading limit.
     **/
    InsufficientTradingAmount: GenericPalletError<Rv>;

    /**
     * Not more than one fee collector per asset id
     **/
    FeeCollectorWithAssetAlreadyUsed: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `NFT`'s errors
   **/
  nft: {
    /**
     * Count of items overflown
     **/
    NoAvailableItemId: GenericPalletError<Rv>;

    /**
     * Count of collections overflown
     **/
    NoAvailableCollectionId: GenericPalletError<Rv>;

    /**
     * Collection still contains minted tokens
     **/
    TokenCollectionNotEmpty: GenericPalletError<Rv>;

    /**
     * Collection does not exist
     **/
    CollectionUnknown: GenericPalletError<Rv>;

    /**
     * Item does not exist
     **/
    ItemUnknown: GenericPalletError<Rv>;

    /**
     * Operation not permitted
     **/
    NotPermitted: GenericPalletError<Rv>;

    /**
     * ID reserved for runtime
     **/
    IdReserved: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Marketplace`'s errors
   **/
  marketplace: {
    /**
     * Account is not the owner of the token
     **/
    NotTheTokenOwner: GenericPalletError<Rv>;

    /**
     * Cannot buy a token from yourself
     **/
    BuyFromSelf: GenericPalletError<Rv>;

    /**
     * Token is currently not for sale
     **/
    NotForSale: GenericPalletError<Rv>;

    /**
     * Collection or item does not exist
     **/
    CollectionOrItemUnknown: GenericPalletError<Rv>;

    /**
     * Offer is lower than the minimum threshold
     **/
    OfferTooLow: GenericPalletError<Rv>;

    /**
     * No offer for this token found from the user
     **/
    UnknownOffer: GenericPalletError<Rv>;

    /**
     * Offer is no longer valid
     **/
    OfferExpired: GenericPalletError<Rv>;

    /**
     * User already made an offer for this token
     **/
    AlreadyOffered: GenericPalletError<Rv>;

    /**
     * User has to be offer maker or token owner to withdraw an offer
     **/
    WithdrawNotAuthorized: GenericPalletError<Rv>;

    /**
     * User has to be the token owner to accept an offer
     **/
    AcceptNotAuthorized: GenericPalletError<Rv>;

    /**
     * Royalty can be set only once
     **/
    RoyaltyAlreadySet: GenericPalletError<Rv>;

    /**
     * Royalty not in 0-9_999 range
     **/
    NotInRange: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `TransactionPause`'s errors
   **/
  transactionPause: {
    /**
     * can not pause
     **/
    CannotPause: GenericPalletError<Rv>;

    /**
     * invalid character encoding
     **/
    InvalidCharacter: GenericPalletError<Rv>;

    /**
     * pallet name or function name is too long
     **/
    NameTooLong: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Router`'s errors
   **/
  router: {
    /**
     * The trading limit has been reached
     **/
    TradingLimitReached: GenericPalletError<Rv>;

    /**
     * The the max number of trades limit is reached
     **/
    MaxTradesExceeded: GenericPalletError<Rv>;

    /**
     * The AMM pool is not supported for executing trades
     **/
    PoolNotSupported: GenericPalletError<Rv>;

    /**
     * The user has not enough balance to execute the trade
     **/
    InsufficientBalance: GenericPalletError<Rv>;

    /**
     * The calculation of route trade amounts failed in the underlying AMM
     **/
    RouteCalculationFailed: GenericPalletError<Rv>;

    /**
     * The route is invalid
     **/
    InvalidRoute: GenericPalletError<Rv>;

    /**
     * The route update was not successful
     **/
    RouteUpdateIsNotSuccessful: GenericPalletError<Rv>;

    /**
     * Route contains assets that has no oracle data
     **/
    RouteHasNoOracle: GenericPalletError<Rv>;

    /**
     * The route execution failed in the underlying AMM
     **/
    InvalidRouteExecution: GenericPalletError<Rv>;

    /**
     * Trading same assets is not allowed.
     **/
    NotAllowed: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `XYKLiquidityMining`'s errors
   **/
  xykLiquidityMining: {
    /**
     * Nft pallet didn't return an owner.
     **/
    CantFindDepositOwner: GenericPalletError<Rv>;

    /**
     * Account balance of XYK pool shares is not sufficient.
     **/
    InsufficientXykSharesBalance: GenericPalletError<Rv>;

    /**
     * XYK pool does not exist
     **/
    XykPoolDoesntExist: GenericPalletError<Rv>;

    /**
     * Account is not deposit owner.
     **/
    NotDepositOwner: GenericPalletError<Rv>;

    /**
     * XYK did not return assets for given pool id
     **/
    CantGetXykAssets: GenericPalletError<Rv>;

    /**
     * Deposit data not found
     **/
    DepositDataNotFound: GenericPalletError<Rv>;

    /**
     * Calculated reward to claim is 0.
     **/
    ZeroClaimedRewards: GenericPalletError<Rv>;

    /**
     * Asset is not in the `AssetPair`.
     **/
    AssetNotInAssetPair: GenericPalletError<Rv>;

    /**
     * Provided `AssetPair` is not used by the deposit.
     **/
    InvalidAssetPair: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `XYKWarehouseLM`'s errors
   **/
  xykWarehouseLM: {
    /**
     * Global farm does not exist.
     **/
    GlobalFarmNotFound: GenericPalletError<Rv>;

    /**
     * Yield farm does not exist.
     **/
    YieldFarmNotFound: GenericPalletError<Rv>;

    /**
     * Multiple claims in the same period is not allowed.
     **/
    DoubleClaimInPeriod: GenericPalletError<Rv>;

    /**
     * Liquidity mining is canceled.
     **/
    LiquidityMiningCanceled: GenericPalletError<Rv>;

    /**
     * Liquidity mining is not canceled.
     **/
    LiquidityMiningIsActive: GenericPalletError<Rv>;

    /**
     * Liquidity mining is in `active` or `terminated` state and action cannot be completed.
     **/
    LiquidityMiningIsNotStopped: GenericPalletError<Rv>;

    /**
     * LP shares amount is not valid.
     **/
    InvalidDepositAmount: GenericPalletError<Rv>;

    /**
     * Account is not allowed to perform action.
     **/
    Forbidden: GenericPalletError<Rv>;

    /**
     * Yield farm multiplier can't be 0.
     **/
    InvalidMultiplier: GenericPalletError<Rv>;

    /**
     * Yield farm with given `amm_pool_id` already exists in global farm.
     **/
    YieldFarmAlreadyExists: GenericPalletError<Rv>;

    /**
     * Loyalty curve's initial reward percentage is not valid. Valid range is: [0, 1).
     **/
    InvalidInitialRewardPercentage: GenericPalletError<Rv>;

    /**
     * One or more yield farms exist in global farm.
     **/
    GlobalFarmIsNotEmpty: GenericPalletError<Rv>;

    /**
     * Farm's `incentivized_asset` is missing in provided asset pair.
     **/
    MissingIncentivizedAsset: GenericPalletError<Rv>;

    /**
     * Reward currency balance is not sufficient.
     **/
    InsufficientRewardCurrencyBalance: GenericPalletError<Rv>;

    /**
     * Blocks per period can't be 0.
     **/
    InvalidBlocksPerPeriod: GenericPalletError<Rv>;

    /**
     * Yield per period can't be 0.
     **/
    InvalidYieldPerPeriod: GenericPalletError<Rv>;

    /**
     * Total rewards is less than `MinTotalFarmRewards`.
     **/
    InvalidTotalRewards: GenericPalletError<Rv>;

    /**
     * Planned yielding periods is less than `MinPlannedYieldingPeriods`.
     **/
    InvalidPlannedYieldingPeriods: GenericPalletError<Rv>;

    /**
     * Maximum number of locks reached for deposit.
     **/
    MaxEntriesPerDeposit: GenericPalletError<Rv>;

    /**
     * Trying to lock LP shares into already locked yield farm.
     **/
    DoubleLock: GenericPalletError<Rv>;

    /**
     * Yield farm entry doesn't exist for given deposit.
     **/
    YieldFarmEntryNotFound: GenericPalletError<Rv>;

    /**
     * Max number of yield farms in global farm was reached. Global farm can't accept new
     * yield farms until some yield farm is not removed from storage.
     **/
    GlobalFarmIsFull: GenericPalletError<Rv>;

    /**
     * Invalid min. deposit was set for global farm.
     **/
    InvalidMinDeposit: GenericPalletError<Rv>;

    /**
     * Price adjustment multiplier can't be 0.
     **/
    InvalidPriceAdjustment: GenericPalletError<Rv>;

    /**
     * Account creation from id failed.
     **/
    ErrorGetAccountId: GenericPalletError<Rv>;

    /**
     * Value of deposited shares amount in reward currency is bellow min. limit.
     **/
    IncorrectValuedShares: GenericPalletError<Rv>;

    /**
     * `reward_currency` is not registered in asset registry.
     **/
    RewardCurrencyNotRegistered: GenericPalletError<Rv>;

    /**
     * `incentivized_asset` is not registered in asset registry.
     **/
    IncentivizedAssetNotRegistered: GenericPalletError<Rv>;

    /**
     * Action cannot be completed because unexpected error has occurred. This should be reported
     * to protocol maintainers.
     **/
    InconsistentState: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `CollatorRewards`'s errors
   **/
  collatorRewards: {
    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Broadcast`'s errors
   **/
  broadcast: {
    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `EmaOracle`'s errors
   **/
  emaOracle: {
    TooManyUniqueEntries: GenericPalletError<Rv>;
    OnTradeValueZero: GenericPalletError<Rv>;
    OracleNotFound: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Currencies`'s errors
   **/
  currencies: {
    /**
     * Unable to convert the Amount type into Balance.
     **/
    AmountIntoBalanceFailed: GenericPalletError<Rv>;

    /**
     * Balance is too low.
     **/
    BalanceTooLow: GenericPalletError<Rv>;

    /**
     * Deposit result is not expected
     **/
    DepositFailed: GenericPalletError<Rv>;

    /**
     * Operation is not supported for this currency
     **/
    NotSupported: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `Tokens`'s errors
   **/
  tokens: {
    /**
     * The balance is too low
     **/
    BalanceTooLow: GenericPalletError<Rv>;

    /**
     * Cannot convert Amount into Balance type
     **/
    AmountIntoBalanceFailed: GenericPalletError<Rv>;

    /**
     * Failed because liquidity restrictions due to locking
     **/
    LiquidityRestrictions: GenericPalletError<Rv>;

    /**
     * Failed because the maximum locks was exceeded
     **/
    MaxLocksExceeded: GenericPalletError<Rv>;

    /**
     * Transfer/payment would kill account
     **/
    KeepAlive: GenericPalletError<Rv>;

    /**
     * Value too low to create account due to existential deposit
     **/
    ExistentialDeposit: GenericPalletError<Rv>;

    /**
     * Beneficiary account must pre-exist
     **/
    DeadAccount: GenericPalletError<Rv>;
    TooManyReserves: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `OrmlXcm`'s errors
   **/
  ormlXcm: {
    /**
     * The message and destination combination was not recognized as being
     * reachable.
     **/
    Unreachable: GenericPalletError<Rv>;

    /**
     * The message and destination was recognized as being reachable but
     * the operation could not be completed.
     **/
    SendFailure: GenericPalletError<Rv>;

    /**
     * The version of the `Versioned` value used is not able to be
     * interpreted.
     **/
    BadVersion: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `XTokens`'s errors
   **/
  xTokens: {
    /**
     * Asset has no reserve location.
     **/
    AssetHasNoReserve: GenericPalletError<Rv>;

    /**
     * Not cross-chain transfer.
     **/
    NotCrossChainTransfer: GenericPalletError<Rv>;

    /**
     * Invalid transfer destination.
     **/
    InvalidDest: GenericPalletError<Rv>;

    /**
     * Currency is not cross-chain transferable.
     **/
    NotCrossChainTransferableCurrency: GenericPalletError<Rv>;

    /**
     * The message's weight could not be determined.
     **/
    UnweighableMessage: GenericPalletError<Rv>;

    /**
     * XCM execution failed.
     **/
    XcmExecutionFailed: GenericPalletError<Rv>;

    /**
     * Could not re-anchor the assets to declare the fees for the
     * destination chain.
     **/
    CannotReanchor: GenericPalletError<Rv>;

    /**
     * Could not get ancestry of asset reserve location.
     **/
    InvalidAncestry: GenericPalletError<Rv>;

    /**
     * The Asset is invalid.
     **/
    InvalidAsset: GenericPalletError<Rv>;

    /**
     * The destination `Location` provided cannot be inverted.
     **/
    DestinationNotInvertible: GenericPalletError<Rv>;

    /**
     * The version of the `Versioned` value used is not able to be
     * interpreted.
     **/
    BadVersion: GenericPalletError<Rv>;

    /**
     * We tried sending distinct asset and fee but they have different
     * reserve chains.
     **/
    DistinctReserveForAssetAndFee: GenericPalletError<Rv>;

    /**
     * The fee is zero.
     **/
    ZeroFee: GenericPalletError<Rv>;

    /**
     * The transfering asset amount is zero.
     **/
    ZeroAmount: GenericPalletError<Rv>;

    /**
     * The number of assets to be sent is over the maximum.
     **/
    TooManyAssetsBeingSent: GenericPalletError<Rv>;

    /**
     * The specified index does not exist in a Assets struct.
     **/
    AssetIndexNonExistent: GenericPalletError<Rv>;

    /**
     * Fee is not enough.
     **/
    FeeNotEnough: GenericPalletError<Rv>;

    /**
     * Not supported Location
     **/
    NotSupportedLocation: GenericPalletError<Rv>;

    /**
     * MinXcmFee not registered for certain reserve location
     **/
    MinXcmFeeNotDefined: GenericPalletError<Rv>;

    /**
     * Asset transfer is limited by RateLimiter.
     **/
    RateLimited: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
  /**
   * Pallet `UnknownTokens`'s errors
   **/
  unknownTokens: {
    /**
     * The balance is too low.
     **/
    BalanceTooLow: GenericPalletError<Rv>;

    /**
     * The operation will cause balance to overflow.
     **/
    BalanceOverflow: GenericPalletError<Rv>;

    /**
     * Unhandled asset.
     **/
    UnhandledAsset: GenericPalletError<Rv>;

    /**
     * Generic pallet error
     **/
    [error: string]: GenericPalletError<Rv>;
  };
}
