// Generated by dedot cli

import type { GenericSubstrateApi, GenericChainKnownTypes, RpcLegacy, RpcV2, RpcVersion } from 'dedot/types';
import type { MultiAddress } from 'dedot/codecs';
import type {
  AssetHubPolkadotRuntimeRuntimeCall,
  SpRuntimeMultiSignature,
  FrameSystemExtensionsCheckNonZeroSender,
  FrameSystemExtensionsCheckSpecVersion,
  FrameSystemExtensionsCheckTxVersion,
  FrameSystemExtensionsCheckGenesis,
  FrameSystemExtensionsCheckMortality,
  FrameSystemExtensionsCheckNonce,
  FrameSystemExtensionsCheckWeight,
  PalletAssetConversionTxPaymentChargeAssetTxPayment,
  FrameMetadataHashExtensionCheckMetadataHash,
} from './types.js';
import { ChainConsts } from './consts.js';
import { ChainStorage } from './query.js';
import { ChainJsonRpcApis } from './json-rpc.js';
import { ChainErrors } from './errors.js';
import { ChainEvents } from './events.js';
import { RuntimeApis } from './runtime.js';
import { ChainViewFunctions } from './view-functions.js';
import { ChainTx } from './tx.js';

export * from './types.js';

interface ChainKnownTypes extends GenericChainKnownTypes {
  Address: MultiAddress;
  Signature: SpRuntimeMultiSignature;
  RuntimeCall: AssetHubPolkadotRuntimeRuntimeCall;
  Extra: [
    FrameSystemExtensionsCheckNonZeroSender,
    FrameSystemExtensionsCheckSpecVersion,
    FrameSystemExtensionsCheckTxVersion,
    FrameSystemExtensionsCheckGenesis,
    FrameSystemExtensionsCheckMortality,
    FrameSystemExtensionsCheckNonce,
    FrameSystemExtensionsCheckWeight,
    PalletAssetConversionTxPaymentChargeAssetTxPayment,
    FrameMetadataHashExtensionCheckMetadataHash,
  ];
}

export interface VersionedPolkadotAssetHubApi<Rv extends RpcVersion> extends GenericSubstrateApi<Rv> {
  rpc: ChainJsonRpcApis<Rv>;
  consts: ChainConsts<Rv>;
  query: ChainStorage<Rv>;
  errors: ChainErrors<Rv>;
  events: ChainEvents<Rv>;
  call: RuntimeApis<Rv>;
  view: ChainViewFunctions<Rv>;
  tx: ChainTx<Rv>;

  types: ChainKnownTypes;
}

/**
 * @name: PolkadotAssetHubApi
 * @specVersion: 2000002
 **/
export interface PolkadotAssetHubApi {
  legacy: VersionedPolkadotAssetHubApi<RpcLegacy>;
  v2: VersionedPolkadotAssetHubApi<RpcV2>;
}
